package com.ctb.utils;

import java.util.ArrayList;
import java.util.List;

public class Constants {
	public static final String USAGE ="Usage";
	public static final String SENTENCE_FORMATION = "Sentence Formation and Paragraph Development";
	public static final String CAPITALIZATION = "Capitalization, Punctuation, and Writing Conventions";
	public static final String NUMBER_OPERATIONS = "Number and Number Operations";
	public static final String COMPUTAION_ESTIMATION = "Computation and Estimation";
	public static final String MEASUREMENT = "Measurement";
	public static final String GEOMETRY_SPATIAL_SENSE = "Geometry and Spatial Sense";
	public static final String DATA_ANALYSIS = "Data Analysis, Statistics, Probability";
	public static final String PATTERNS_FUNCTIONS_ALGEBRA ="Patterns, Functions, Algebra";
	public static final String PROBLEM_SOLVING ="Problem Solving and Reasoning";
	public static final String RECALL_INFORMATION = "Recall Information";
	public static final String WORDS_IN_CONTEXT = "Words in Context/Construct Meaning";
	public static final String EVALUATE = "Evaluate/Extend Meaning and Interpret Graphic Information";
	public static final String WHOLE_NUMBERS = "Whole Numbers";
	public static final String DECIMALS_FRACTIONS = "Decimals, Fractions, Percents";
	public static final String INTEGERS = "Integers";
	public static final String ALGEBRAIC_OPERATIONS = "Algebraic Operations";
	public static final String CONSTRUCT_MEANING_IN_CONTEXT = "Construct Meaning in Context";
	public static final String INTERNET_EVALUATE_EXTEND = "Interpret, Evaluate, and Extend Meaning";
	public static final String STATISTICS_PROBABILITY = "Statistics and Probability";
	public static final String SENTENCE_PARAGRAPH = "Sentence and Paragraph Development";
	public static final String WRITING_MECHANICS_CONVENTIONS = "Writing Mechanics and Conventions";
	public static final String ADD_WHOLE_NUMBERS = "Add Whole Numbers";
	public static final String CAPITALIZATION1 = "Capitalization";
	public static final String COMPUTATION_IN_CONTEXT = "Computation in Context";
	public static final String CONSONANT = "Consonant";
	public static final String CONSTRUCT_MEANING = "Construct Meaning";
	public static final String DATA_ANALYSIS1 = "Data Analysis";
	public static final String DECIMALS = "Decimals";
	public static final String DIVIDE_WHOLE_NUMBERS = "Divide Whole Numbers";
	public static final String ESTIMATION = "Estimation";
	public static final String EVALUATE_EXTEND_MEANING = "Evaluate/Extend Meaning";
	public static final String FRACTIONS = "Fractions";
	public static final String INTERPRET_GRAPHIC_INFORMATION = "Interpret Graphic Information";
	public static final String MULTIMEANING_WORDS = "Multimeaning Words";
	public static final String MULTIPLY_WHOLE_NUMBERS = "Multiply Whole Numbers";
	public static final String ORDER_OF_OPERATIONS = "Order of Operations";
	public static final String PARAGRAPH_DEVELOPMENT = "Paragraph Development";
	public static final String PERCENTS = "Percents";
	public static final String PREREADING_SKILLS = "Pre-Reading Skills";
	public static final String PUNCTUATION = "Punctuation";
	public static final String SENTENCE_FORMATION1 = "Sentence Formation";
	public static final String SENTENCES_PHRASES_CLAUSES = "Sentences, Phrases, Clauses";
	public static final String STRUCTURAL_UNIT = "Structural Unit";
	public static final String SUBTRACT_WHOLE_NUMBERS = "Subtract Whole Numbers";
	public static final String VOWEL = "Vowel";
	public static final String WORD_MEANING = "Word Meaning";
	public static final String WORDS_IN_CONTEXT1 = "Words in Context";
	public static final String WRITING_CONVENTIONS1 = "Writing Conventions";
	public static final List<String> OBJECTIVES = new ArrayList<String>(50);
	
	static {
		OBJECTIVES.add(Constants.RECALL_INFORMATION);
		OBJECTIVES.add(Constants.CONSTRUCT_MEANING_IN_CONTEXT);
		OBJECTIVES.add(Constants.INTERNET_EVALUATE_EXTEND);
		OBJECTIVES.add(Constants.WHOLE_NUMBERS);
		OBJECTIVES.add(Constants.DECIMALS_FRACTIONS);
		OBJECTIVES.add(Constants.INTEGERS);
		OBJECTIVES.add(Constants.ALGEBRAIC_OPERATIONS);
		OBJECTIVES.add(Constants.NUMBER_OPERATIONS);
		OBJECTIVES.add(Constants.COMPUTAION_ESTIMATION);
		OBJECTIVES.add(Constants.MEASUREMENT);
		OBJECTIVES.add(Constants.GEOMETRY_SPATIAL_SENSE);
		OBJECTIVES.add(Constants.STATISTICS_PROBABILITY);
		OBJECTIVES.add(Constants.PATTERNS_FUNCTIONS_ALGEBRA);
		OBJECTIVES.add(Constants.PROBLEM_SOLVING);
		OBJECTIVES.add(Constants.USAGE);
		OBJECTIVES.add(Constants.SENTENCE_PARAGRAPH);
		OBJECTIVES.add(Constants.WRITING_MECHANICS_CONVENTIONS);
		OBJECTIVES.add(Constants.ADD_WHOLE_NUMBERS);
		OBJECTIVES.add(Constants.CAPITALIZATION1);
		OBJECTIVES.add(Constants.COMPUTATION_IN_CONTEXT);
		OBJECTIVES.add(Constants.CONSONANT);
		OBJECTIVES.add(Constants.CONSTRUCT_MEANING);
		OBJECTIVES.add(Constants.DATA_ANALYSIS1);
		OBJECTIVES.add(Constants.DECIMALS);
		OBJECTIVES.add(Constants.DIVIDE_WHOLE_NUMBERS);
		OBJECTIVES.add(Constants.ESTIMATION);
		OBJECTIVES.add(Constants.EVALUATE_EXTEND_MEANING);
		OBJECTIVES.add(Constants.FRACTIONS);
		OBJECTIVES.add(Constants.INTERPRET_GRAPHIC_INFORMATION);
		OBJECTIVES.add(Constants.MULTIMEANING_WORDS);
		OBJECTIVES.add(Constants.MULTIPLY_WHOLE_NUMBERS);
		OBJECTIVES.add(Constants.ORDER_OF_OPERATIONS);
		OBJECTIVES.add(Constants.PARAGRAPH_DEVELOPMENT);
		OBJECTIVES.add(Constants.PERCENTS);
		OBJECTIVES.add(Constants.PREREADING_SKILLS);
		OBJECTIVES.add(Constants.PUNCTUATION);
		OBJECTIVES.add(Constants.SENTENCE_FORMATION1);
		OBJECTIVES.add(Constants.SENTENCES_PHRASES_CLAUSES);
		OBJECTIVES.add(Constants.STRUCTURAL_UNIT);
		OBJECTIVES.add(Constants.SUBTRACT_WHOLE_NUMBERS);
		OBJECTIVES.add(Constants.VOWEL);
		OBJECTIVES.add(Constants.WORD_MEANING);
		OBJECTIVES.add(Constants.WORDS_IN_CONTEXT1);
		OBJECTIVES.add(Constants.WRITING_CONVENTIONS1);
	}
}