package com.ctb.utils;

import java.util.ArrayList;
import java.util.List;

public class Constants {
	public static final String RD_CONSTRUCT_MEANING_IN_CONTEXT = "RD-Construct Meaning in Context";
	public static final String RD_INTERPRET_EVALUATE_AND_EXTEND_MEANING = "RD-Interpret, Evaluate, and Extend Meaning";
	public static final String RD_RECALL_INFORMATION = "RD-Recall Information";
	public static final String RD_CONSTRUCT_MEANING = "RD-Construct Meaning";
	public static final String RD_EVALUATE_EXTEND_MEANING = "RD-Evaluate/Extend Meaning";
	public static final String RD_INTERPRET_GRAPHIC_INFORMATION = "RD-Interpret Graphic Information";
	public static final String RD_PRE_READING_SKILLS = "RD-Pre-Reading Skills";
	public static final String RD_WORDS_IN_CONTEXT = "RD-Words in Context";
	public static final String MC_ALGEBRAIC_OPERATIONS = "MC-Algebraic Operations";
	public static final String MC_DECIMALS_FRACTIONS_PERCENTS = "MC-Decimals, Fractions, Percents";
	public static final String MC_INTEGERS = "MC-Integers";
	public static final String MC_WHOLE_NUMBERS = "MC-Whole Numbers";
	public static final String MC_ADD_WHOLE_NUMBERS = "MC-Add Whole Numbers";
	public static final String MC_DECIMALS = "MC-Decimals";
	public static final String MC_DIVIDE_WHOLE_NUMBERS = "MC-Divide Whole Numbers";
	public static final String MC_FRACTIONS = "MC-Fractions";
	public static final String MC_MULTIPLY_WHOLE_NUMBERS = "MC-Multiply Whole Numbers";
	public static final String MC_ORDER_OF_OPERATIONS = "MC-Order of Operations";
	public static final String MC_PERCENTS = "MC-Percents";
	public static final String MC_SUBTRACT_WHOLE_NUMBERS = "MC-Subtract Whole Numbers";
	public static final String AM_COMPUTATION_AND_ESTIMATION = "AM-Computation and Estimation";
	public static final String AM_GEOMETRY_AND_SPATIAL_SENSE = "AM-Geometry and Spatial Sense";
	public static final String AM_MEASUREMENT = "AM-Measurement";
	public static final String AM_NUMBER_AND_NUMBER_OPERATIONS = "AM-Number and Number Operations";
	public static final String AM_PATTERNS_FUNCTIONS_ALGEBRA = "AM-Patterns, Functions, Algebra";
	public static final String AM_PROBLEM_SOLVING_AND_REASONING = "AM-Problem Solving and Reasoning";
	public static final String AM_STATISTICS_AND_PROBABILITY = "AM-Statistics and Probability";
	public static final String AM_COMPUTATION_IN_CONTEXT = "AM-Computation in Context";
	public static final String AM_DATA_ANALYSIS = "AM-Data Analysis";
	public static final String AM_ESTIMATION = "AM-Estimation";
	public static final String LN_SENTENCE_AND_PARAGRAPH_DEVELOPMENT = "LN-Sentence and Paragraph Development";
	public static final String LN_USAGE = "LN-Usage";
	public static final String LN_WRITING_MECHANICS_AND_CONVENTIONS = "LN-Writing Mechanics and Conventions";
	public static final String LN_CAPITALIZATION = "LN-Capitalization";
	public static final String LN_PARAGRAPH_DEVELOPMENT = "LN-Paragraph Development";
	public static final String LN_PUNCTUATION = "LN-Punctuation";
	public static final String LN_SENTENCE_FORMATION = "LN-Sentence Formation";
	public static final String LN_WRITING_CONVENTIONS = "LN-Writing Conventions";
	public static final String VO_MULTIMEANING_WORDS = "VO-Multimeaning Words";
	public static final String VO_WORD_MEANING = "VO-Word Meaning";
	public static final String VO_WORDS_IN_CONTEXT = "VO-Words in Context";
	public static final String LM_SENTENCES_PHRASES_CLAUSES = "LM-Sentences, Phrases, Clauses";
	public static final String LM_WRITING_CONVENTIONS = "LM-Writing Conventions";
	public static final String SP_CONSONANT = "SP-Consonant";
	public static final String SP_STRUCTURAL_UNIT = "SP-Structural Unit";
	public static final String SP_VOWEL = "SP-Vowel";
	public static final List<String> OBJECTIVES = new ArrayList<String>(50);
	
	static {
		OBJECTIVES.add(Constants.RD_CONSTRUCT_MEANING_IN_CONTEXT);
		OBJECTIVES.add(Constants.RD_INTERPRET_EVALUATE_AND_EXTEND_MEANING);
		OBJECTIVES.add(Constants.RD_RECALL_INFORMATION);
		OBJECTIVES.add(Constants.RD_CONSTRUCT_MEANING);
		OBJECTIVES.add(Constants.RD_EVALUATE_EXTEND_MEANING);
		OBJECTIVES.add(Constants.RD_INTERPRET_GRAPHIC_INFORMATION);
		OBJECTIVES.add(Constants.RD_PRE_READING_SKILLS);
		OBJECTIVES.add(Constants.RD_WORDS_IN_CONTEXT);
		OBJECTIVES.add(Constants.MC_ALGEBRAIC_OPERATIONS);
		OBJECTIVES.add(Constants.MC_DECIMALS_FRACTIONS_PERCENTS);
		OBJECTIVES.add(Constants.MC_INTEGERS);
		OBJECTIVES.add(Constants.MC_WHOLE_NUMBERS);
		OBJECTIVES.add(Constants.MC_ADD_WHOLE_NUMBERS);
		OBJECTIVES.add(Constants.MC_DECIMALS);
		OBJECTIVES.add(Constants.MC_DIVIDE_WHOLE_NUMBERS);
		OBJECTIVES.add(Constants.MC_FRACTIONS);
		OBJECTIVES.add(Constants.MC_MULTIPLY_WHOLE_NUMBERS);
		OBJECTIVES.add(Constants.MC_ORDER_OF_OPERATIONS);
		OBJECTIVES.add(Constants.MC_PERCENTS);
		OBJECTIVES.add(Constants.MC_SUBTRACT_WHOLE_NUMBERS);
		OBJECTIVES.add(Constants.AM_COMPUTATION_AND_ESTIMATION);
		OBJECTIVES.add(Constants.AM_GEOMETRY_AND_SPATIAL_SENSE);
		OBJECTIVES.add(Constants.AM_MEASUREMENT);
		OBJECTIVES.add(Constants.AM_NUMBER_AND_NUMBER_OPERATIONS);
		OBJECTIVES.add(Constants.AM_PATTERNS_FUNCTIONS_ALGEBRA);
		OBJECTIVES.add(Constants.AM_PROBLEM_SOLVING_AND_REASONING);
		OBJECTIVES.add(Constants.AM_STATISTICS_AND_PROBABILITY);
		OBJECTIVES.add(Constants.AM_COMPUTATION_IN_CONTEXT);
		OBJECTIVES.add(Constants.AM_DATA_ANALYSIS);
		OBJECTIVES.add(Constants.AM_ESTIMATION);
		OBJECTIVES.add(Constants.LN_SENTENCE_AND_PARAGRAPH_DEVELOPMENT);
		OBJECTIVES.add(Constants.LN_USAGE);
		OBJECTIVES.add(Constants.LN_WRITING_MECHANICS_AND_CONVENTIONS);
		OBJECTIVES.add(Constants.LN_CAPITALIZATION);
		OBJECTIVES.add(Constants.LN_PARAGRAPH_DEVELOPMENT);
		OBJECTIVES.add(Constants.LN_PUNCTUATION);
		OBJECTIVES.add(Constants.LN_SENTENCE_FORMATION);
		OBJECTIVES.add(Constants.LN_WRITING_CONVENTIONS);
		OBJECTIVES.add(Constants.VO_MULTIMEANING_WORDS);
		OBJECTIVES.add(Constants.VO_WORD_MEANING);
		OBJECTIVES.add(Constants.VO_WORDS_IN_CONTEXT);
		OBJECTIVES.add(Constants.LM_SENTENCES_PHRASES_CLAUSES);
		OBJECTIVES.add(Constants.LM_WRITING_CONVENTIONS);
		OBJECTIVES.add(Constants.SP_CONSONANT);
		OBJECTIVES.add(Constants.SP_STRUCTURAL_UNIT);
		OBJECTIVES.add(Constants.SP_VOWEL);
	}
}