CREATE OR REPLACE PROCEDURE "SP_FETCH_MSS_RETRY_ERRORS"(FETCHSIZE   IN NUMBER,
                                                        TEMP_LOG_ID OUT NUMBER) AS
BEGIN
DECLARE
  V_TMP_LOG_ID             NUMBER;

  CURSOR C1 IS
    SELECT SCORING_INVOKE_LOG_KEY
      FROM SCORING_INVOKE_LOG A
     WHERE A.STATUS = 'Progress'
       AND A.INVOKE_COUNT < 5
       AND NOT EXISTS
     (SELECT 1
              FROM TMP_MSS_ERROR_LOG B
             WHERE A.SCORING_INVOKE_LOG_KEY = B.INVOKE_LOG_KEY)
     ORDER BY A.UPDATED_DATE ASC
       FOR UPDATE SKIP LOCKED;

  TYPE TROWIDTBL IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  VROWIDTBL TROWIDTBL;

BEGIN
  SELECT SEQ_TMP_MSS_LOG_ID.NEXTVAL INTO V_TMP_LOG_ID FROM DUAL;

  OPEN C1;
  FETCH C1 BULK COLLECT
    INTO VROWIDTBL LIMIT FETCHSIZE;
  CLOSE C1;
  
  FORALL I IN VROWIDTBL.FIRST .. VROWIDTBL.LAST
    INSERT INTO TMP_MSS_ERROR_LOG (INVOKE_LOG_KEY, TMP_ID)  VALUES (VROWIDTBL(I), V_TMP_LOG_ID);

  TEMP_LOG_ID := V_TMP_LOG_ID;
END;
END;
