CREATE TABLE PRISM_WS_AUDIT_LOG (
INVOKE_ID NUMBER PRIMARY KEY,
ROSTER_ID NUMBER NOT NULL,
STUDENT_ID NUMBER NOT NULL,
SESSION_ID NUMBER NOT NULL,
WS_INVOKE_TIMESTAMP DATE DEFAULT SYSDATE,
WS_RESPONSE_TIMESTAMP DATE,
RETRY_PROCESS VARCHAR2(10), 
RETRY_ERROR_LOG_ID NUMBER,
PRISM_PROCESS_ID VARCHAR2(50),
PRISM_PARTITION_ID VARCHAR2(50),
STATUS_CODE VARCHAR2(50),
MESSAGE VARCHAR2(500), 
WS_TYPE VARCHAR2(50) NOT NULL,
WS_ERROR_LOG_KEY NUMBER, 
OAS_XML_SENT CLOB,
PRISM_RESPONSE CLOB,
UPDATED_DATE_TIME DATE
)
/
create index PRISM_AUDIT_ROSTER_ID on PRISM_WS_AUDIT_LOG (ROSTER_ID)
/
create sequence SEQ_PRISM_AUDIT_LOG_ID
minvalue 1
maxvalue 999999999999999999999999999
start with 1000
increment by 1
cache 20
/