#!/bin/sh

XML_FILENAME=$1
XSL_FILENAME=$2
FOP_PROGRAM_FILENAME=../fop.sh
XALAN_PROGRAM_FILENAME=../xalan.sh
NEW_PDF_FILENAME=$1__$2.fo
echo "Generating $NEW_PDF_FILENAME from $XML_FILENAME using $XSL_FILENAME..."
$XALAN_PROGRAM_FILENAME xml/$XML_FILENAME xsl/$XSL_FILENAME pdf/$NEW_PDF_FILENAME
echo "...done"
