<%@ page import="java.io.*, java.util.*"%>
<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8" isErrorPage="true"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui:html>
  <head>
    <title>Error</title>
  </head>
  <body>
    <p>
      An error has occurred:
    </p>
    <blockquote>
      <netui:span value="${requestScope.errorMessage}" defaultValue=""/>
      <br/>
      <netui:exceptions showMessage="true"/>
    </blockquote>
  </body>
</netui:html>

<!-- Some browsers will not display this page unless the response status code is 200. -->
<% response.setStatus(200); %>
