CREATE TYPE BMTSYNC_ASSIGNMENT_TYP IS OBJECT  (
    CUSTOMER_ID       INTEGER,
    TEST_ADMIN_ID     INTEGER,
    STUDENT_ID        INTEGER,
    TEST_ROSTER_ID    INTEGER,
    UPDATED_DATE_TIME DATE
);
/


