#!/bin/sh

XALAN_PROGRAM_FILENAME=../xalan.sh
XML_FILENAME=../originals/xml/$1
XSL_FILENAME=xsl/$2
CORRECT_PDF_FILENAME=../originals/pdf/$1__$2.fo
ATTEMPTED_PDF_FILENAME=test.fo
DIFF_LOG_FILENAME=diff.log

>$DIFF_LOG_FILENAME

echo "Generating $ATTEMPTED_PDF_FILENAME from $XML_FILENAME using $XSL_FILENAME..."
$XALAN_PROGRAM_FILENAME $XML_FILENAME $XSL_FILENAME $ATTEMPTED_PDF_FILENAME
echo "Comparing with original PDF..."
if diff $ATTEMPTED_PDF_FILENAME $CORRECT_PDF_FILENAME>>$DIFF_LOG_FILENAME
then echo "$XML_FILENAME, $XSL_FILENAME: SUCCESS"
else echo "$XML_FILENAME, $XSL_FILENAME: FAILED (files differ: see $DIFF_LOG_FILENAME)"
fi
