CREATE TABLE FORM_ASSIGNMENT_LOOKUP (
       TEST_CATALOG_ID  INTEGER NOT NULL,
       PRODUCT_ID INTEGER NOT NULL,
       TEST_NAME VARCHAR2(64) NOT NULL,
       SCREEN_READER_FORMS VARCHAR2(64) NOT NULL,
       NON_SCREEN_READER_FORMS VARCHAR2(64) NOT NULL,
       ACTIVATION_STATUS VARCHAR2(4) NOT NULL,
       CREATED_DATE_TIME  DATE,
       UPDATED_DATE_TIME  DATE
)
/
