package com.ctb.dataaccess;

public interface SiteEnrollmentSQL {
	String GET_SITE_SURVEY_ID=  " SELECT SITE_SURVEY_ID FROM SITE_SURVEY WHERE UPPER(SITE_TYPE) = 'SCHOOL' AND SITE_ID = ? AND SITE_PATH = ? AND CUSTOMER_ID= ?";
	
	String GET_SCHOOL_DETAILS_FROM_OAS ="SELECT  DISTINCT ORG_SCHOOL.ORG_NODE_CODE AS SCHOOL_ID,S.GRADE AS GRADE,ORG_SCHOOL.ORG_NODE_NAME  AS SCHOOL_NAME,ORG_DISTRICT.ORG_NODE_NAME AS DISTRICT_NAME "
										+ " FROM "
										+ " TEST_ADMIN TA,TEST_ROSTER TR, STUDENT S,ORG_NODE ORG , ORG_NODE_PARENT ONP ,ORG_NODE_PARENT ONP1,ORG_NODE ORG_SCHOOL ,ORG_NODE ORG_DISTRICT " 
										+ " WHERE " 
										+ " TA.TEST_ADMIN_ID=TR.TEST_ADMIN_ID " 
										+ " AND TR.STUDENT_ID=S.STUDENT_ID " 
										+ " AND TR.ORG_NODE_ID=ORG.ORG_NODE_ID "
										+ " AND ORG.ORG_NODE_ID=ONP.ORG_NODE_ID AND ORG.ACTIVATION_STATUS='AC'"
										+ " AND ORG_SCHOOL.ORG_NODE_ID=ONP.PARENT_ORG_NODE_ID AND ORG_SCHOOL.ACTIVATION_STATUS='AC' "
										+ " AND ORG_SCHOOL.ORG_NODE_ID=ONP1.ORG_NODE_ID AND ORG_DISTRICT.ACTIVATION_STATUS='AC' "
										+ " AND ORG_DISTRICT.ORG_NODE_ID=ONP1.PARENT_ORG_NODE_ID" 
										+ " AND TA.PRODUCT_ID= ? AND TA.CUSTOMER_ID= ?  AND TA.ACTIVATION_STATUS='AC' AND " 
										+ " TR.ACTIVATION_STATUS='AC' AND TR.TEST_COMPLETION_STATUS NOT IN ('SC', 'NT')" 
										+ " GROUP BY ORG_SCHOOL.ORG_NODE_CODE,S.GRADE,ORG_SCHOOL.ORG_NODE_NAME,ORG_DISTRICT.ORG_NODE_NAME " 
										+ " HAVING (COUNT(TR.TEST_ROSTER_ID)>0) ORDER BY ORG_SCHOOL.ORG_NODE_CODE ";
	
	
	String  UPDATE_SITE_SURVEY_ENROLLMENT= "UPDATE SITE_SURVEY_ENROLLMENT SET THIRD_GRADE_PREVIOUS_YEAR = ? ," +
			" FOURTH_GRADE_PREVIOUS_YEAR = ? ," +
			" FIFTH_GRADE_PREVIOUS_YEAR = ? ," +
			" SIXTH_GRADE_PREVIOUS_YEAR = ? ," +
			" SEVENTH_GRADE_PREVIOUS_YEAR = ? ," +
			" EIGHTH_GRADE_PREVIOUS_YEAR = ?  WHERE SITE_SURVEY_ID = ?";
}
