
package com.ctb.prism.web.controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SampleWebservice", targetNamespace = "http://controller.web.prism.ctb.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SampleWebservice {


    /**
     * 
     * @param studentListTO
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadStudentData", targetNamespace = "http://controller.web.prism.ctb.com/", className = "com.ctb.prism.web.controller.LoadStudentData")
    @ResponseWrapper(localName = "loadStudentDataResponse", targetNamespace = "http://controller.web.prism.ctb.com/", className = "com.ctb.prism.web.controller.LoadStudentDataResponse")
    public String loadStudentData(
        @WebParam(name = "StudentListTO", targetNamespace = "")
        StudentListTO studentListTO);

}
