
package com.ctb.prism.web.controller;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StudentDataloadService", targetNamespace = "http://controller.web.prism.ctb.com/", wsdlLocation = "file:/C:/Users/d-suvonkar_dam/workspace/OASWSClient/src/com/ctb/prism/web/wsdl/StudentDataloadService.wsdl")
public class StudentDataloadService
    extends Service
{

    private final static URL STUDENTDATALOADSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/d-suvonkar_dam/workspace/OASWSClient/src/com/ctb/prism/web/wsdl/StudentDataloadService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        STUDENTDATALOADSERVICE_WSDL_LOCATION = url;
    }

    public StudentDataloadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentDataloadService() {
        super(STUDENTDATALOADSERVICE_WSDL_LOCATION, new QName("http://controller.web.prism.ctb.com/", "StudentDataloadService"));
    }

    /**
     * 
     * @return
     *     returns SampleWebservice
     */
    @WebEndpoint(name = "SampleWebservicePort")
    public SampleWebservice getSampleWebservicePort() {
        return (SampleWebservice)super.getPort(new QName("http://controller.web.prism.ctb.com/", "SampleWebservicePort"), SampleWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SampleWebservice
     */
    @WebEndpoint(name = "SampleWebservicePort")
    public SampleWebservice getSampleWebservicePort(WebServiceFeature... features) {
        return (SampleWebservice)super.getPort(new QName("http://controller.web.prism.ctb.com/", "SampleWebservicePort"), SampleWebservice.class, features);
    }

}
