package com.ctb.db;

public interface AuditTrailSQL {
	
	String UPDATE_DATAEXPORT_INTERMIDEATE_JOB_STATUS = " UPDATE data_export SET LAST_UPDATE_STATUS = ?, LAST_UPDATE_TIME = SYSDATE, MESSAGE = ? WHERE EXPORT_ID = ?  ";
	String UPDATE_DATAEXPORT_JOB_STATUS             = " UPDATE data_export SET STATUS = ?, LAST_UPDATE_STATUS = ?, LAST_UPDATE_TIME = SYSDATE, MESSAGE = ? WHERE EXPORT_ID = ?  ";
	String UPDATE_TEST_ROSTER = "UPDATE TEST_ROSTER SET STUDENT_EXPORTED = 'T' WHERE TEST_ROSTER_ID IN( <<ROSTER_ID_LIST>> )" ;
	

}
