ALTER TRIGGER LIC_CREATE_SESSION_ORGNODE DISABLE
/
ALTER TRIGGER LIC_CREATE_SUBTEST_ORGNODE DISABLE
/
ALTER TRIGGER LIC_DELETE_SESSION_ORGNODE DISABLE
/
ALTER TRIGGER LIC_DELETE_SUBTEST_ORGNODE DISABLE
/
ALTER TRIGGER LIC_UPDATE_SESSION_ORGNODE DISABLE
/
ALTER TRIGGER LIC_UPDATE_SUBTEST_ORGNODE DISABLE
/