create table LM_OUTAGE_EXTRACT_DATA
(
  CUSTOMER_ID              INTEGER,
  ORG_NODE_ID              INTEGER,
  ORG_NODE_NAME            VARCHAR2(264),
  ORG_NODE_LEVEL           INTEGER,
  ORG_NODE_CATEGORY_NAME   VARCHAR2(64),
  PARENT_ORG_NODE_ID       INTEGER,
  PARENT_ORG_NODE_NAME     VARCHAR2(264),
  LIC_AVL_IN_DB            INTEGER,
  CUM_LIC_AVL_IN_DB        INTEGER,
  TIER2_PURCHASE           INTEGER,
  CUM_TIER2_PURCHASE       INTEGER,
  LIC_TO_BE_RELEASED       INTEGER,
  CUM_LIC_TO_BE_RELEASED   INTEGER,
  LIC_RESERVED_AT_NODE     INTEGER,
  CUM_LIC_RESERVED         INTEGER,
  LIC_CONSUMED_AT_NODE     INTEGER,
  CUM_LIC_CONSUMED         INTEGER,
  NODE_LVL_AVAILABLE       INTEGER,
  CUM_AVAILABLE            INTEGER,
  NODE_NET_AVAILABLE       INTEGER,
  CUM_NET_AVAILABLE        INTEGER,
  EXTRACT_DATE_TIME        DATE default SYSDATE,
  ACTIVATION_STATUS        VARCHAR2(10),
  SUBTEST_MODEL            VARCHAR2(10),
  LIC_MOD_CONSUMED_AT_NODE INTEGER,
  CUM_LIC_MOD_CONSUMED     INTEGER
)/

create table LM_OUTAGE_EXTRACT_LOG
(
  CUSTOMER_ID INTEGER,
  MESSAGE     VARCHAR2(1024),
  LOG_TIME    DATE
)/