package com.ctb.hibernate.persist;

import java.io.Serializable;

    public class ItemSetItemCompositeId implements Serializable {
        private String itemId;
        private Long itemSetId;

    /**
     * @hibernate.property
     * column="ITEM_ID"
     * not-null="true"
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * @hibernate.property
     * column="ITEM_SET_ID"
     * not-null="true"
     */
    public Long getItemSetId() {
        return itemSetId;
    }

    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    public void setItemSetId(Long itemSetId) {
        this.itemSetId = itemSetId;
    }

    public int hashCode() {
        // TODO: Generated by HibernateGen.rb
        return toString().hashCode();
    }

    public boolean equals(Object object) {
        // TODO: Generated by HibernateGen.rb
        return toString().equals(object.toString());
    }

    public String toString() {
        // TODO: Generated by HibernateGen.rb
        return "" + itemSetId.toString() + "|" + itemId.toString();
    }
}
