package com.ctb.hibernate.persist;

import java.io.Serializable;

    public class ItemSetProductCompositeId implements Serializable {
        private Long itemSetId;
        private Long productId;

    /**
     * @hibernate.property
     * column="ITEM_SET_ID"
     * not-null="true"
     */
    public Long getItemSetId() {
        return itemSetId;
    }

    /**
     * @hibernate.property
     * column="PRODUCT_ID"
     * not-null="true"
     */
    public Long getProductId() {
        return productId;
    }

    public void setItemSetId(Long itemSetId) {
        this.itemSetId = itemSetId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public int hashCode() {
        // TODO: Generated by HibernateGen.rb
        return toString().hashCode();
    }

    public boolean equals(Object object) {
        // TODO: Generated by HibernateGen.rb
        return toString().equals(object.toString());
    }

    public String toString() {
        // TODO: Generated by HibernateGen.rb
        return "" + itemSetId.toString() + "|" + productId.toString();
    }
}
