package com.ctb.hibernate.persist;

import java.io.Serializable;

    public class ItemMediaCompositeId implements Serializable {
        private String itemId;
        private String mediaType;

    /**
     * @hibernate.property
     * column="ITEM_ID"
     * not-null="true"
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * @hibernate.property
     * column="MEDIA_TYPE"
     * not-null="true"
     */
    public String getMediaType() {
        return mediaType;
    }

    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    public int hashCode() {
        // TODO: Generated by HibernateGen.rb
        return toString().hashCode();
    }

    public boolean equals(Object object) {
        // TODO: Generated by HibernateGen.rb
        return toString().equals(object.toString());
    }

    public String toString() {
        // TODO: Generated by HibernateGen.rb
        return "" + mediaType.toString() + "|" + itemId.toString();
    }
}
