package com.ctb.hibernate.persist;

import java.io.Serializable;

    public class ItemSetAncestorCompositeId implements Serializable {
        private Long ancestorItemSetId;
        private Long itemSetId;

    /**
     * @hibernate.property
     * column="ANCESTOR_ITEM_SET_ID"
     * not-null="true"
     */
    public Long getAncestorItemSetId() {
        return ancestorItemSetId;
    }

    /**
     * @hibernate.property
     * column="ITEM_SET_ID"
     * not-null="true"
     */
    public Long getItemSetId() {
        return itemSetId;
    }

    public void setAncestorItemSetId(Long ancestorItemSetId) {
        this.ancestorItemSetId = ancestorItemSetId;
    }

    public void setItemSetId(Long itemSetId) {
        this.itemSetId = itemSetId;
    }

    public int hashCode() {
        // TODO: Generated by HibernateGen.rb
        return toString().hashCode();
    }

    public boolean equals(Object object) {
        // TODO: Generated by HibernateGen.rb
        return toString().equals(object.toString());
    }

    public String toString() {
        // TODO: Generated by HibernateGen.rb
        return "" + itemSetId.toString() + "|" + ancestorItemSetId.toString();
    }
}
