CREATE OR REPLACE PROCEDURE SP_SET_MODULE_ID
AUTHID CURRENT_USER as
MAX_SEQ_NO INTEGER;
TEMP_SEQ_NO INTEGER;
TEMP_MODULE_ID VARCHAR2(4);
NEXT_MODULE_ID VARCHAR2(4);
Create_str varchar2(4000);
BEGIN
Create_str:='Create table PEID_TEMP_STORE(Curr_MOD_ID Varchar2(4))';
execute immediate Create_str;
end ;
/
