CREATE OR REPLACE PROCEDURE sp_seq_id_misc(in_TABLE_NAME IN VARCHAR2,o_SEQ_NO OUT INTEGER)
IS
   V_NEXTVAL INTEGER;
BEGIN
IF in_TABLE_NAME='ORG_NODE' THEN
 SELECT SEQ_ORG_NODE_ID.NEXTVAL INTO V_NEXTVAL FROM DUAL;
ELSIF in_TABLE_NAME='USERS' THEN
SELECT SEQ_USER_ID.NEXTVAL INTO V_NEXTVAL FROM DUAL;
END IF;
 o_SEQ_NO:=V_NEXTVAL;
END sp_seq_id_misc;
/
