CREATE OR REPLACE PROCEDURE SP_SEQ_ID(in_TABLE_NAME IN VARCHAR2,o_SEQ_NO OUT INTEGER)
IS
   V_NEXTVAL INTEGER;
BEGIN
IF in_TABLE_NAME='ORG_NODE' THEN
 SELECT SEQ_ORG_NODE_ID.NEXTVAL INTO V_NEXTVAL FROM DUAL;
ELSIF in_TABLE_NAME='CUSTOMER_RESEARCH_NAME' THEN
SELECT SEQ_CUSTOMER_RESEARCH_NAME_ID.NEXTVAL INTO V_NEXTVAL FROM DUAL;
END IF;
 o_SEQ_NO:=V_NEXTVAL;
END SP_SEQ_ID;
/
