INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q1',1,'A','Hispanic');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q1',1,'B','Not Hispanic');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q2',2,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q2',2,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q3',3,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q3',3,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q4',4,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q4',4,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q5',5,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q5',5,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q6',6,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q6',6,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q14',14,'A','Y');/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q14',14,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q15',15,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q15',15,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q16',16,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q16',16,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q17',17,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q17',17,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q18',18,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q18',18,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q19',19,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q19',19,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q20',20,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q20',20,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q21',21,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q21',21,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q22',22,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q22',22,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q23',23,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q23',23,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q25',25,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q25',25,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q26',26,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q26',26,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q27',27,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q27',27,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q28',28,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q28',28,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q29',29,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q29',29,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30',30,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30',30,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30',30,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30',30,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30',30,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31',31,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31',31,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31',31,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31',31,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31',31,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32',32,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32',32,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32',32,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32',32,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32',32,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33',33,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33',33,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33',33,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33',33,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33',33,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34',34,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34',34,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34',34,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34',34,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34',34,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q35',35,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q35',35,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q36',36,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q36',36,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q37',37,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q37',37,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q38',38,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q38',38,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q39',39,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q39',39,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q40',40,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q40',40,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q41',41,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q41',41,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q42',42,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q42',42,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q43',43,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q43',43,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q44',44,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q44',44,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45',45,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45',45,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45',45,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45',45,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45',45,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46',46,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46',46,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46',46,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46',46,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46',46,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47',47,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47',47,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47',47,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47',47,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47',47,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48',48,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48',48,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48',48,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48',48,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48',48,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49',49,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49',49,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49',49,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49',49,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49',49,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50',50,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50',50,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50',50,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50',50,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50',50,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51',51,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51',51,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51',51,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51',51,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51',51,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52',52,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52',52,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52',52,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52',52,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52',52,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53',53,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53',53,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53',53,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53',53,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53',53,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54',54,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54',54,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54',54,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54',54,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54',54,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q57',57,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q57',57,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q58',58,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q58',58,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q59',59,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q59',59,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q60',60,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q60',60,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q1.SP',1,'A','Hispanic');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q1.SP',1,'B','Not Hispanic');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q2.SP',2,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q2.SP',2,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q3.SP',3,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q3.SP',3,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q4.SP',4,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q4.SP',4,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q5.SP',5,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q5.SP',5,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q6.SP',6,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q6.SP',6,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q14.SP',14,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q14.SP',14,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q15.SP',15,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q15.SP',15,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q16.SP',16,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q16.SP',16,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q17.SP',17,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q17.SP',17,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q18.SP',18,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q18.SP',18,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q19.SP',19,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q19.SP',19,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q20.SP',20,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q20.SP',20,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q21.SP',21,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q21.SP',21,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q22.SP',22,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q22.SP',22,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q23.SP',23,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q23.SP',23,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q25.SP',25,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q25.SP',25,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q26.SP',26,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q26.SP',26,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q27.SP',27,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q27.SP',27,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q28.SP',28,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q28.SP',28,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q29.SP',29,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q29.SP',29,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30.SP',30,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30.SP',30,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30.SP',30,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30.SP',30,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30.SP',30,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31.SP',31,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31.SP',31,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31.SP',31,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31.SP',31,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31.SP',31,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32.SP',32,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32.SP',32,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32.SP',32,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32.SP',32,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32.SP',32,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33.SP',33,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33.SP',33,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33.SP',33,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33.SP',33,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33.SP',33,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34.SP',34,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34.SP',34,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34.SP',34,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34.SP',34,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34.SP',34,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q35.SP',35,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q35.SP',35,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q36.SP',36,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q36.SP',36,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q37.SP',37,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q37.SP',37,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q38.SP',38,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q38.SP',38,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q39.SP',39,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q39.SP',39,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q40.SP',40,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q40.SP',40,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q41.SP',41,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q41.SP',41,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q42.SP',42,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q42.SP',42,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q43.SP',43,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q43.SP',43,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q44.SP',44,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q44.SP',44,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45.SP',45,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45.SP',45,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45.SP',45,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45.SP',45,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45.SP',45,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46.SP',46,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46.SP',46,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46.SP',46,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46.SP',46,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46.SP',46,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47.SP',47,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47.SP',47,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47.SP',47,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47.SP',47,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47.SP',47,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48.SP',48,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48.SP',48,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48.SP',48,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48.SP',48,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48.SP',48,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49.SP',49,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49.SP',49,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49.SP',49,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49.SP',49,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49.SP',49,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50.SP',50,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50.SP',50,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50.SP',50,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50.SP',50,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50.SP',50,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51.SP',51,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51.SP',51,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51.SP',51,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51.SP',51,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51.SP',51,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52.SP',52,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52.SP',52,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52.SP',52,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52.SP',52,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52.SP',52,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53.SP',53,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53.SP',53,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53.SP',53,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53.SP',53,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53.SP',53,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54.SP',54,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54.SP',54,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54.SP',54,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54.SP',54,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54.SP',54,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q57.SP',57,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q57.SP',57,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q58.SP',58,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q58.SP',58,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q59.SP',59,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q59.SP',59,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q60.SP',60,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q60.SP',60,'B','N');
/