INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q1',1,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q2',2,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q3',3,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q4',4,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q5',5,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q6',6,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q7',7,'Examinee_ph');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q8',8,'Stdnt_Addrss');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q9',9,'Student_APT');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q10',10,'Student_City');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q11',11,'Student_St');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q12',12,'Student_ZIP');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q13',13,'Stdnt_Ctn_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q14',14,'Pr_Cnty_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q15',15,'Pr_Schl_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q16',16,'Pr_Mtry_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q17',17,'Pr_Rlgn_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q18',18,'Pr_Stdy_Book');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q19',19,'Pr_Onln_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q20',20,'Pr_Homeschl');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q21',21,'Pr_Tutor');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q22',22,'Pr_Slf_Tht');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q23',23,'Rdns_Assmnt');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q24',24,'Edu_Ctr_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q25',25,'Rd_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q26',26,'Wr_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q27',27,'Ma_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q28',28,'Sc_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q29',29,'SS_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q30',30,'Rd_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q31',31,'Wr_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q32',32,'Ma_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q33',33,'Sc_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q34',34,'SS_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q35',35,'Rd_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q36',36,'Wr_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q37',37,'Ma_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q38',38,'Sc_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q39',39,'SS_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q40',40,'Rd_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q41',41,'Wr_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q42',42,'Ma_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q43',43,'Sc_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q44',44,'SS_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q45',45,'Rd_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q46',46,'Wr_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q47',47,'Ma_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q48',48,'Sc_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q49',49,'SS_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q50',50,'Rd_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q51',51,'Wr_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q52',52,'Ma_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q53',53,'Sc_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q54',54,'SS_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q55',55,'Hghst_Edu');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q56',56,'Hme_Language');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q57',57,'Exmne_Wver');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q58',58,'Exmne_Ack');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q59',59,'Exmne_Progrs');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q60',60,'Addi_Qstn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q61',61,'Local_Use_1');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q62',62,'Local_Use_2');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q63',63,'Local_Use_3');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q64',64,'Local_Use_4');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q65',65,'Local_Use_5');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q66',66,'Local_Use_6');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q67',67,'Local_Use_7');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q68',68,'Local_Use_8');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q69',69,'Local_Use_9');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q70',70,'Local_Use_10');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q71',71,'Local_Use_11');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q72',72,'Local_Use_12');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q73',73,'Local_Use_13');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q74',74,'Local_Use_14');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q75',75,'Local_Use_15');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q76',76,'Local_Use_16');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q77',77,'Local_Use_17');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q78',78,'Local_Use_18');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q79',79,'Local_Use_19');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4501,'TASC.BD.JAN14.Q80',80,'Local_Use_20');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q1',1,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q2',2,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q3',3,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q4',4,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q5',5,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q6',6,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q7',7,'Examinee_ph');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q8',8,'Stdnt_Addrss');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q9',9,'Student_APT');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q10',10,'Student_City');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q11',11,'Student_St');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q12',12,'Student_ZIP');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q13',13,'Stdnt_Ctn_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q14',14,'Pr_Cnty_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q15',15,'Pr_Schl_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q16',16,'Pr_Mtry_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q17',17,'Pr_Rlgn_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q18',18,'Pr_Stdy_Book');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q19',19,'Pr_Onln_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q20',20,'Pr_Homeschl');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q21',21,'Pr_Tutor');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q22',22,'Pr_Slf_Tht');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q23',23,'Rdns_Assmnt');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q24',24,'Edu_Ctr_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q25',25,'Rd_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q26',26,'Wr_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q27',27,'Ma_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q28',28,'Sc_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q29',29,'SS_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q30',30,'Rd_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q31',31,'Wr_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q32',32,'Ma_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q33',33,'Sc_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q34',34,'SS_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q35',35,'Rd_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q36',36,'Wr_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q37',37,'Ma_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q38',38,'Sc_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q39',39,'SS_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q40',40,'Rd_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q41',41,'Wr_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q42',42,'Ma_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q43',43,'Sc_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q44',44,'SS_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q45',45,'Rd_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q46',46,'Wr_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q47',47,'Ma_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q48',48,'Sc_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q49',49,'SS_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q50',50,'Rd_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q51',51,'Wr_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q52',52,'Ma_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q53',53,'Sc_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q54',54,'SS_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q55',55,'Hghst_Edu');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q56',56,'Hme_Language');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q57',57,'Exmne_Wver');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q58',58,'Exmne_Ack');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q59',59,'Exmne_Progrs');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q60',60,'Addi_Qstn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q61',61,'Local_Use_1');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q62',62,'Local_Use_2');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q63',63,'Local_Use_3');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q64',64,'Local_Use_4');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q65',65,'Local_Use_5');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q66',66,'Local_Use_6');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q67',67,'Local_Use_7');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q68',68,'Local_Use_8');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q69',69,'Local_Use_9');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q70',70,'Local_Use_10');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q71',71,'Local_Use_11');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q72',72,'Local_Use_12');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q73',73,'Local_Use_13');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q74',74,'Local_Use_14');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q75',75,'Local_Use_15');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q76',76,'Local_Use_16');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q77',77,'Local_Use_17');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q78',78,'Local_Use_18');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q79',79,'Local_Use_19');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4502,'TASC.BD.JAN14.Q80',80,'Local_Use_20');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q1',1,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q2',2,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q3',3,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q4',4,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q5',5,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q6',6,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q7',7,'Examinee_ph');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q8',8,'Stdnt_Addrss');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q9',9,'Student_APT');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q10',10,'Student_City');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q11',11,'Student_St');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q12',12,'Student_ZIP');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q13',13,'Stdnt_Ctn_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q14',14,'Pr_Cnty_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q15',15,'Pr_Schl_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q16',16,'Pr_Mtry_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q17',17,'Pr_Rlgn_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q18',18,'Pr_Stdy_Book');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q19',19,'Pr_Onln_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q20',20,'Pr_Homeschl');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q21',21,'Pr_Tutor');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q22',22,'Pr_Slf_Tht');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q23',23,'Rdns_Assmnt');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q24',24,'Edu_Ctr_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q25',25,'Rd_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q26',26,'Wr_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q27',27,'Ma_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q28',28,'Sc_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q29',29,'SS_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q30',30,'Rd_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q31',31,'Wr_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q32',32,'Ma_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q33',33,'Sc_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q34',34,'SS_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q35',35,'Rd_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q36',36,'Wr_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q37',37,'Ma_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q38',38,'Sc_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q39',39,'SS_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q40',40,'Rd_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q41',41,'Wr_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q42',42,'Ma_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q43',43,'Sc_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q44',44,'SS_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q45',45,'Rd_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q46',46,'Wr_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q47',47,'Ma_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q48',48,'Sc_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q49',49,'SS_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q50',50,'Rd_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q51',51,'Wr_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q52',52,'Ma_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q53',53,'Sc_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q54',54,'SS_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q55',55,'Hghst_Edu');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q56',56,'Hme_Language');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q57',57,'Exmne_Wver');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q58',58,'Exmne_Ack');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q59',59,'Exmne_Progrs');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q60',60,'Addi_Qstn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q61',61,'Local_Use_1');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q62',62,'Local_Use_2');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q63',63,'Local_Use_3');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q64',64,'Local_Use_4');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q65',65,'Local_Use_5');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q66',66,'Local_Use_6');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q67',67,'Local_Use_7');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q68',68,'Local_Use_8');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q69',69,'Local_Use_9');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q70',70,'Local_Use_10');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q71',71,'Local_Use_11');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q72',72,'Local_Use_12');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q73',73,'Local_Use_13');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q74',74,'Local_Use_14');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q75',75,'Local_Use_15');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q76',76,'Local_Use_16');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q77',77,'Local_Use_17');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q78',78,'Local_Use_18');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q79',79,'Local_Use_19');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4503,'TASC.BD.JAN14.Q80',80,'Local_Use_20');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q1',1,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q2',2,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q3',3,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q4',4,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q5',5,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q6',6,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q7',7,'Examinee_ph');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q8',8,'Stdnt_Addrss');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q9',9,'Student_APT');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q10',10,'Student_City');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q11',11,'Student_St');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q12',12,'Student_ZIP');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q13',13,'Stdnt_Ctn_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q14',14,'Pr_Cnty_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q15',15,'Pr_Schl_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q16',16,'Pr_Mtry_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q17',17,'Pr_Rlgn_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q18',18,'Pr_Stdy_Book');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q19',19,'Pr_Onln_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q20',20,'Pr_Homeschl');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q21',21,'Pr_Tutor');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q22',22,'Pr_Slf_Tht');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q23',23,'Rdns_Assmnt');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q24',24,'Edu_Ctr_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q25',25,'Rd_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q26',26,'Wr_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q27',27,'Ma_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q28',28,'Sc_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q29',29,'SS_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q30',30,'Rd_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q31',31,'Wr_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q32',32,'Ma_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q33',33,'Sc_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q34',34,'SS_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q35',35,'Rd_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q36',36,'Wr_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q37',37,'Ma_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q38',38,'Sc_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q39',39,'SS_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q40',40,'Rd_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q41',41,'Wr_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q42',42,'Ma_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q43',43,'Sc_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q44',44,'SS_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q45',45,'Rd_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q46',46,'Wr_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q47',47,'Ma_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q48',48,'Sc_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q49',49,'SS_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q50',50,'Rd_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q51',51,'Wr_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q52',52,'Ma_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q53',53,'Sc_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q54',54,'SS_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q55',55,'Hghst_Edu');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q56',56,'Hme_Language');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q57',57,'Exmne_Wver');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q58',58,'Exmne_Ack');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q59',59,'Exmne_Progrs');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q60',60,'Addi_Qstn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q61',61,'Local_Use_1');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q62',62,'Local_Use_2');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q63',63,'Local_Use_3');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q64',64,'Local_Use_4');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q65',65,'Local_Use_5');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q66',66,'Local_Use_6');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q67',67,'Local_Use_7');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q68',68,'Local_Use_8');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q69',69,'Local_Use_9');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q70',70,'Local_Use_10');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q71',71,'Local_Use_11');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q72',72,'Local_Use_12');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q73',73,'Local_Use_13');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q74',74,'Local_Use_14');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q75',75,'Local_Use_15');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q76',76,'Local_Use_16');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q77',77,'Local_Use_17');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q78',78,'Local_Use_18');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q79',79,'Local_Use_19');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4504,'TASC.BD.JAN14.Q80',80,'Local_Use_20');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q1',1,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q2',2,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q3',3,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q4',4,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q5',5,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q6',6,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q7',7,'Examinee_ph');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q8',8,'Stdnt_Addrss');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q9',9,'Student_APT');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q10',10,'Student_City');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q11',11,'Student_St');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q12',12,'Student_ZIP');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q13',13,'Stdnt_Ctn_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q14',14,'Pr_Cnty_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q15',15,'Pr_Schl_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q16',16,'Pr_Mtry_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q17',17,'Pr_Rlgn_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q18',18,'Pr_Stdy_Book');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q19',19,'Pr_Onln_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q20',20,'Pr_Homeschl');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q21',21,'Pr_Tutor');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q22',22,'Pr_Slf_Tht');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q23',23,'Rdns_Assmnt');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q24',24,'Edu_Ctr_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q25',25,'Rd_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q26',26,'Wr_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q27',27,'Ma_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q28',28,'Sc_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q29',29,'SS_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q30',30,'Rd_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q31',31,'Wr_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q32',32,'Ma_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q33',33,'Sc_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q34',34,'SS_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q35',35,'Rd_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q36',36,'Wr_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q37',37,'Ma_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q38',38,'Sc_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q39',39,'SS_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q40',40,'Rd_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q41',41,'Wr_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q42',42,'Ma_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q43',43,'Sc_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q44',44,'SS_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q45',45,'Rd_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q46',46,'Wr_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q47',47,'Ma_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q48',48,'Sc_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q49',49,'SS_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q50',50,'Rd_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q51',51,'Wr_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q52',52,'Ma_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q53',53,'Sc_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q54',54,'SS_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q55',55,'Hghst_Edu');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q56',56,'Hme_Language');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q57',57,'Exmne_Wver');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q58',58,'Exmne_Ack');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q59',59,'Exmne_Progrs');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q60',60,'Addi_Qstn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q61',61,'Local_Use_1');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q62',62,'Local_Use_2');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q63',63,'Local_Use_3');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q64',64,'Local_Use_4');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q65',65,'Local_Use_5');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q66',66,'Local_Use_6');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q67',67,'Local_Use_7');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q68',68,'Local_Use_8');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q69',69,'Local_Use_9');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q70',70,'Local_Use_10');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q71',71,'Local_Use_11');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q72',72,'Local_Use_12');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q73',73,'Local_Use_13');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q74',74,'Local_Use_14');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q75',75,'Local_Use_15');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q76',76,'Local_Use_16');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q77',77,'Local_Use_17');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q78',78,'Local_Use_18');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q79',79,'Local_Use_19');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4505,'TASC.BD.JAN14.Q80',80,'Local_Use_20');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q1',1,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q2',2,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q3',3,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q4',4,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q5',5,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q6',6,'Rslvd_Ethnic');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q7',7,'Examinee_ph');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q8',8,'Stdnt_Addrss');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q9',9,'Student_APT');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q10',10,'Student_City');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q11',11,'Student_St');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q12',12,'Student_ZIP');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q13',13,'Stdnt_Ctn_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q14',14,'Pr_Cnty_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q15',15,'Pr_Schl_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q16',16,'Pr_Mtry_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q17',17,'Pr_Rlgn_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q18',18,'Pr_Stdy_Book');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q19',19,'Pr_Onln_Prog');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q20',20,'Pr_Homeschl');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q21',21,'Pr_Tutor');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q22',22,'Pr_Slf_Tht');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q23',23,'Rdns_Assmnt');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q24',24,'Edu_Ctr_Cd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q25',25,'Rd_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q26',26,'Wr_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q27',27,'Ma_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q28',28,'Sc_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q29',29,'SS_Passed');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q30',30,'Rd_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q31',31,'Wr_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q32',32,'Ma_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q33',33,'Sc_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q34',34,'SS_Times_Tkn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q35',35,'Rd_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q36',36,'Wr_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q37',37,'Ma_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q38',38,'Sc_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q39',39,'SS_Retake');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q40',40,'Rd_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q41',41,'Wr_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q42',42,'Ma_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q43',43,'Sc_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q44',44,'SS_cls_3_mts');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q45',45,'Rd_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q46',46,'Wr_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q47',47,'Ma_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q48',48,'Sc_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q49',49,'SS_mnths');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q50',50,'Rd_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q51',51,'Wr_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q52',52,'Ma_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q53',53,'Sc_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q54',54,'SS_Grd');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q55',55,'Hghst_Edu');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q56',56,'Hme_Language');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q57',57,'Exmne_Wver');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q58',58,'Exmne_Ack');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q59',59,'Exmne_Progrs');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q60',60,'Addi_Qstn');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q61',61,'Local_Use_1');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q62',62,'Local_Use_2');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q63',63,'Local_Use_3');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q64',64,'Local_Use_4');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q65',65,'Local_Use_5');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q66',66,'Local_Use_6');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q67',67,'Local_Use_7');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q68',68,'Local_Use_8');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q69',69,'Local_Use_9');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q70',70,'Local_Use_10');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q71',71,'Local_Use_11');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q72',72,'Local_Use_12');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q73',73,'Local_Use_13');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q74',74,'Local_Use_14');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q75',75,'Local_Use_15');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q76',76,'Local_Use_16');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q77',77,'Local_Use_17');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q78',78,'Local_Use_18');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q79',79,'Local_Use_19');
/
INSERT INTO STUDENT_SURVEY_QUESTION (PRODUCT_ID, QUESTION_ID,QUESTION_ORDER,QUESTION_CODE) VALUES (4506,'TASC.BD.JAN14.Q80',80,'Local_Use_20');
/