INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q1',1,'A','Hispanic');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q1',1,'B','Not Hispanic');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q2',2,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q2',2,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q3',3,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q3',3,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q4',4,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q4',4,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q5',5,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q5',5,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q6',6,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q6',6,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q14',14,'A','Y');/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q14',14,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q15',15,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q15',15,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q16',16,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q16',16,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q17',17,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q17',17,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q18',18,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q18',18,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q19',19,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q19',19,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q20',20,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q20',20,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q21',21,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q21',21,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q22',22,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q22',22,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q23',23,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q23',23,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q25',25,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q25',25,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q26',26,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q26',26,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q27',27,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q27',27,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q28',28,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q28',28,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q29',29,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q29',29,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30',30,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30',30,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30',30,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30',30,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q30',30,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31',31,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31',31,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31',31,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31',31,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q31',31,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32',32,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32',32,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32',32,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32',32,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q32',32,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33',33,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33',33,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33',33,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33',33,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q33',33,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34',34,'A','0');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34',34,'B','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34',34,'C','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34',34,'D','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q34',34,'E','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q35',35,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q35',35,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q36',36,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q36',36,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q37',37,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q37',37,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q38',38,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q38',38,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q39',39,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q39',39,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q40',40,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q40',40,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q41',41,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q41',41,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q42',42,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q42',42,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q43',43,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q43',43,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q44',44,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q44',44,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45',45,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45',45,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45',45,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45',45,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q45',45,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46',46,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46',46,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46',46,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46',46,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q46',46,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47',47,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47',47,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47',47,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47',47,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q47',47,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48',48,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48',48,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48',48,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48',48,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q48',48,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49',49,'A','1');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49',49,'B','2');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49',49,'C','3');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49',49,'D','4');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q49',49,'E','5');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50',50,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50',50,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50',50,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50',50,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q50',50,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51',51,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51',51,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51',51,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51',51,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q51',51,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52',52,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52',52,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52',52,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52',52,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q52',52,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53',53,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53',53,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53',53,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53',53,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q53',53,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54',54,'A','A');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54',54,'B','B');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54',54,'C','C');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54',54,'D','D');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q54',54,'E','F');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q57',57,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q57',57,'B',null);
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q58',58,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q58',58,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q59',59,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q59',59,'B','N');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q60',60,'A','Y');
/
INSERT INTO STUDENT_SURVEY_QUESTION_OPTION (QUESTION_ID,QUESTION_ORDER,QUESTION_OPTION_OAS, QUESTION_OPTION_PRISM) VALUES ('TASC.BD.JAN14.Q60',60,'B','N');
/