
--Insert Master Data for Objective Details

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('1', '01', 'Reading Literature');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('1','02','Reading Informational Text');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('1','03','Key Ideas and Details');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('1','04','Craft and Structure');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('1','05','Integration of Knowledge and Ideas');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('1','06','Vocabulary Acquisition and Use');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('2','07','Editing and Revising');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('2','08','Essay Writing');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('4','01','Number and Quantity');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('4','02','Algebra');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('4','03','Functions');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('4','04','Geometry');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('4','05','Statistics and Probability');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('5','01','Physical Sciences');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('5','02','Life Sciences');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('5','03','Earth and Space Sciences');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('6','01','US History');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('6','02','World History');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('6','03','Civics and Government');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('6','04','Geography');

INSERT INTO OBJECTIVE_DETAILS (CONTENT_CODE, OBJECTIVE_CODE, OBJECTIVE_TITLE) VALUES ('6','05','Economics');














