INSERT INTO FORM_DIM(FORMID, NAME, PRODUCT_TYPEID) VALUES(54, 'D2', (SELECT PRODUCT_TYPEID FROM PRODUCT_TYPE_DIM WHERE NAME = 'TASC'));
/
INSERT INTO FORM_DIM(FORMID, NAME, PRODUCT_TYPEID) VALUES(55, 'E2', (SELECT PRODUCT_TYPEID FROM PRODUCT_TYPE_DIM WHERE NAME = 'TASC'));
/
INSERT INTO FORM_DIM(FORMID, NAME, PRODUCT_TYPEID) VALUES(56, 'F2', (SELECT PRODUCT_TYPEID FROM PRODUCT_TYPE_DIM WHERE NAME = 'TASC'));
/