CREATE OR REPLACE TRIGGER UPDATE_ROSTER_FORM_ON_ACCOM
AFTER UPDATE OF SCREEN_READER ON OAS.STUDENT_ACCOMMODATION
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
when (NEW.SCREEN_READER = 'T')
DECLARE

  FUNCTION VALIDATEGACUSTOMER RETURN VARCHAR2 AS
  V_IS_GA_CUSTOMER VARCHAR2(2) := NULL;
  BEGIN
  
    SELECT DECODE(COUNT(1), 0, 'F', 'T')
      INTO V_IS_GA_CUSTOMER
      FROM STUDENT STUD, CUSTOMER CUST, CUSTOMER_CONFIGURATION CC
     WHERE STUD.STUDENT_ID = :NEW.STUDENT_ID
       AND CUST.CUSTOMER_ID = STUD.CUSTOMER_ID
       AND EXISTS
     (SELECT 1
              FROM CUSTOMER_CONFIGURATION CC
             WHERE CC.CUSTOMER_ID = CUST.CUSTOMER_ID
               AND CC.CUSTOMER_CONFIGURATION_NAME = 'GA_Customer'
               AND CC.DEFAULT_VALUE = 'T');
               
    RETURN V_IS_GA_CUSTOMER;
  END VALIDATEGACUSTOMER;

BEGIN
  IF :NEW.SCREEN_READER IS NOT NULL AND (:OLD.SCREEN_READER <> :NEW.SCREEN_READER) THEN
    IF VALIDATEGACUSTOMER() = 'T' THEN
     
      INSERT INTO ROSTER_FORM_REASSIGN_INPUT
        (STUDENT_ID, JOB_STATUS, ATTEMPTED_COUNTER)
      VALUES
        (:NEW.STUDENT_ID,
         'Prepared',
         0);
    END IF;
  END IF;
END;
