package com.ctb.contentBridge.core.publish.hibernate.persist;

import java.io.Serializable;

    public class DatapointConditionCodeCompositeId implements Serializable {
        private Long conditionCodeId;
        private Long datapointId;

    /**
     * @hibernate.property
     * column="CONDITION_CODE_ID"
     * not-null="true"
     */
    public Long getConditionCodeId() {
        return conditionCodeId;
    }

    /**
     * @hibernate.property
     * column="DATAPOINT_ID"
     * not-null="true"
     */
    public Long getDatapointId() {
        return datapointId;
    }

    public void setConditionCodeId(Long conditionCodeId) {
        this.conditionCodeId = conditionCodeId;
    }

    public void setDatapointId(Long datapointId) {
        this.datapointId = datapointId;
    }

    public int hashCode() {
        // TODO: Generated by HibernateGen.rb
        return toString().hashCode();
    }

    public boolean equals(Object object) {
        // TODO: Generated by HibernateGen.rb
        return toString().equals(object.toString());
    }

    public String toString() {
        // TODO: Generated by HibernateGen.rb
        return "" + datapointId.toString() + "|" + conditionCodeId.toString();
    }
}
