package com.ctb.contentBridge.core.publish.hibernate.persist;

import java.io.Serializable;

    public class ItemSetParentCompositeId implements Serializable {
        private Long itemSetId;
        private Long parentItemSetId;

    /**
     * @hibernate.property
     * column="ITEM_SET_ID"
     * not-null="true"
     */
    public Long getItemSetId() {
        return itemSetId;
    }

    /**
     * @hibernate.property
     * column="PARENT_ITEM_SET_ID"
     * not-null="true"
     */
    public Long getParentItemSetId() {
        return parentItemSetId;
    }

    public void setItemSetId(Long itemSetId) {
        this.itemSetId = itemSetId;
    }

    public void setParentItemSetId(Long parentItemSetId) {
        this.parentItemSetId = parentItemSetId;
    }

    public int hashCode() {
        // TODO: Generated by HibernateGen.rb
        return toString().hashCode();
    }

    public boolean equals(Object object) {
        // TODO: Generated by HibernateGen.rb
        return toString().equals(object.toString());
    }

    public String toString() {
        // TODO: Generated by HibernateGen.rb
        return "" + parentItemSetId.toString() + "|" + itemSetId.toString();
    }
}
