<%@ page import="java.io.*, java.util.*"%>
<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8" isErrorPage="true"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<netui-data:declareBundle bundlePath="oasResources" name="oas"/>
<netui-data:declareBundle bundlePath="widgetResources" name="widgets"/>

<netui-template:template templatePage="/resources/jsp/oas_template.jsp">
    <netui-template:setAttribute name="title" value="Error"/>
    <netui-template:section name="bodySection">
	<form method="post" action="begin.do">
		<input type="hidden" id="menuId" name="menuId" value="" />

        <table border="0" width="97%" style="margin:15px auto;">
	<tr>
	<td>
		<table>
			<tr>
				<td>
	                <div style="background-color: #ffc; border-color: #000; border-style: solid; border-width: 1px; padding: 10px;">
	                    <table>
	                        <tr>
	                            <td valign="center">
	                                <img src="<%=request.getContextPath()%>/resources/images/messaging/icon_error.gif" border="0" width="16" height="16">&nbsp;&nbsp;
	                            </td>
	                            <td valign="center">
	                                <font style="color: red; font-size:12px; font-weight:bold">
	          							<netui:span value="${bundle.oas['system.error.message']}"/>
	                                </font>
	                            </td>
	                        </tr>
	                    </table>
	                </div>
				</td>
			</tr>
		</table>
	</td>    
	</tr>
	</table>
    <script type="text/javascript">
		$(document).ready(function(){
			setMenuActive("organizations", "organizationsLink");
			}
		);
	</script>  
  </form>

<!-- Some browsers will not display this page unless the response status code is 200. -->
<% response.setStatus(200); %>

</netui-template:section>
</netui-template:template>
