var INVALID_NUMBER_CHARS = "Please re-enter your string with these characters: A-Z, a-z, 0-9, space";
var INVALID_NAME_CHARS = "Please re-enter your information with only these characters: A-Z, a-z, 0-9, /, \\, -, ', (, ), &, +, comma, period, space";
var REQUIRED_TEXT = "Please enter/select this value to continue.";
var REQUIRED_TEXT_MULTIPLE = "Please enter/select these values to continue.";
var INVALID_NUMBER_FORMAT = "Please enter phone and fax with numeric characters, with no spaces. Acceptable characters are 0-9.";
var invalid_char_message = "One or more fields contain invalid formats or invalid values:";
var INVALID_FORMAT_TITLE = "One or more fields contain invalid formats or invalid values:"; 
var INVALID_ADDRESS_CHARS  = "Please re-enter your information with only these characters: A-Z, a-z, 0-9, #, /, \\, -, ', (, ), &, +, comma, period, space";
var INVALID_CITY_CHARS  = "Please re-enter your information with only these characters: A-Z, a-z, 0-9, /, \\, -, ', (, ), &, +, comma, period, space";
var INVALID_EMAIL  = "Please enter a valid email address.";
var INVALID_NUMERIC_FORMAT = "Please re-enter numeric fields in valid format.";
var INVALID_DATES_MSG = "Please make sure the end date is after the desired start date.";
var TAC_SIXCHARS="TACs must be at least 6 characters long.";
var TAC_SPECIAL_CHAR_NOTALLOWED_HEADER = "Special characters are not allowed in Test Access Code(s)";
var TAC_SPECIAL_CHAR_NOTALLOWED = "Please remove them in Test Access Code(s)."
var TAC_IDENTICAL_TESTACCESSCODES_HEADER ="Identical Test Access Codes";
var TAC_IDENTICAL_TEST_ACCESSCODES1 ="Test Access Codes must be unique for each subtest to allow and enforce breaks.";
var TAC_IDENTICAL_TEST_ACCESSCODES2 = "Make sure each Test Access Code is different, or uncheck the Allow Test Breaks check box, to not allow breaks during this test session.";
var TAC_MISSING_TEST_ACCESSCODE_HEADER = "Missing Test Access Code.";
var TAC_MISSING_TEST_ACCESSCODE= "For security purposes, a Test Access Code is required for each test. Enter a Test Access Code for this test and then Proceed.";
var TAC_MISSING_TEST_ACCESSCODES_HEADER= "Missing Test Access Code(s).";
var TAC_MISSING_TEST_ACCESSCODES1 = "For security purposes, a Test Access Code is required for each subtest.";
var TAC_MISSING_TEST_ACCESSCODES2= "If you allow student breaks, make sure there is a unique Test Access Code for each subtest, and then Proceed.";
var STUDENTS_DELETED = "student(s) removed from the Student Test Roster."
var STUDENTS_ADDED = "student(s) added to the Student Test Roster."
var ALL_STUDENTS_DELETED = "All students removed from the Student Test Roster."