--SCRIPT TO CREATE STUDENT QUEUE TABLE AND STUDENT QUEUE
DECLARE
   TYPE REF_CURSOR_TYPE IS REF CURSOR;
   PRESULTCURSOR  REF_CURSOR_TYPE;
   
BEGIN
   PKG_BMTSYNC_QUEUETABLE.CREATEQUEUESFORAPI('STUDENT', 'STUDENT_MESSAGE_TYP', PRESULTCURSOR);
END;
/


DECLARE
   TYPE REF_CURSOR_TYPE IS REF CURSOR;
   PRESULTCURSOR  REF_CURSOR_TYPE;
   
BEGIN
   PKG_BMTSYNC_QUEUETABLE.CREATEQUEUESFORAPI('ASSIGNMENT', 'BMTSYNC_ASSIGNMENT_TYP', PRESULTCURSOR);
END;
/


DECLARE
   TYPE REF_CURSOR_TYPE IS REF CURSOR;
   PRESULTCURSOR  REF_CURSOR_TYPE;
   
BEGIN
   PKG_BMTSYNC_QUEUETABLE.CREATEQUEUESFORAPI('TESTADMIN', 'BMTSYNC_TESTADMIN_TYP', PRESULTCURSOR);
END;
/


/*
DECLARE

BEGIN
   --PKG_AQ_NOTIFICATION.Add_Subscriber('AQ_STUDENT', 'Student_Subscriber');
   PKG_AQ_NOTIFICATION.Register_Subscriber('AQ_STUDENT', 'Student_Subscriber', 'plsql://DEMO_DEQUEUE_NOTIFICATION');
   --PKG_AQ_NOTIFICATION.Unregister_Subscriber('AQ_STUDENT', 'Student_Subscriber', 'plsql://DEMO_DEQUEUE_NOTIFICATION');   
END;
/
*/


