CREATE TABLE BMTSYNC_RETRY_FREQUENCY (
                        No_of_Attempt  NUMBER NOT NULL,
                        DELAY_IN_MINS  NUMBER NOT NULL                        

		);



DELETE FROM BMTSYNC_RETRY_FREQUENCY;

INSERT INTO BMTSYNC_RETRY_FREQUENCY VALUES (0, 1);
INSERT INTO BMTSYNC_RETRY_FREQUENCY VALUES (1, 1);
INSERT INTO BMTSYNC_RETRY_FREQUENCY VALUES (2, 1);
INSERT INTO BMTSYNC_RETRY_FREQUENCY VALUES (3, 5);
INSERT INTO BMTSYNC_RETRY_FREQUENCY VALUES (4, 15);
INSERT INTO BMTSYNC_RETRY_FREQUENCY VALUES (5, 60);

COMMIT;

