CREATE TABLE BMTSYNC_CUSTOMER
(
  CUSTOMER_ID     INTEGER not null,
  CUSTOMER_NAME   VARCHAR2(50) not null,
  URL_ENDPOINT    VARCHAR2(2000),
  SYNC_PRIORITY   VARCHAR2(50),
  FETCH_RESPONSES CHAR(1) default 'N'
);



ALTER TABLE BMTSYNC_CUSTOMER ADD (SYNC_PRIORITY VARCHAR2(50));
ALTER TABLE BMTSYNC_CUSTOMER ADD CONSTRAINT CHECK_SYNC_PRIORITY CHECK ( SYNC_PRIORITY IN ('HIGH', 'MEDIUM','LOW'));
ALTER TABLE BMTSYNC_CUSTOMER ADD (FETCH_RESPONSES CHAR(1) DEFAULT 'N');

DELETE FROM BMTSYNC_CUSTOMER;

INSERT INTO BMTSYNC_CUSTOMER(Customer_Id, Customer_Name, URL_ENDPOINT) VALUES 
(7496,'INDIANA', 'http://insync-bmt.prod.ec2-ctb.com/');

INSERT INTO BMTSYNC_CUSTOMER(Customer_Id, Customer_Name, URL_ENDPOINT) VALUES 
(21264, 'GEORGIA', 'http://gasync-bmt.prod.ec2-ctb.com/');


INSERT INTO BMTSYNC_CUSTOMER(Customer_Id, Customer_Name, URL_ENDPOINT) VALUES 
(22446,'CTBQA ISTEP 2015', 'http://insync-bmt.prod.ec2-ctb.com/');

INSERT INTO BMTSYNC_CUSTOMER(Customer_Id, Customer_Name, URL_ENDPOINT) VALUES 
(22465, 'CTBQA GA 2015', 'http://gasync-bmt.prod.ec2-ctb.com/');

COMMIT;

