#!/bin/sh

PATH=/local/apps/oas/proto/jre1.6.0_26/bin:$PATH
export PATH
JAVA_HOME=/local/apps/oas/proto/jre1.6.0_26
export JAVA_HOME
JRE_HOME=/local/apps/oas/proto/jre1.6.0_26
export JRE_HOME
java -version
/local/apps/oas/proto/storage/apache-cassandra-0.7.6-2/bin/cassandra

