ALTER TABLE STUDENT_ITEM_SET_STATUS
 ADD (TMS_UPDATE  VARCHAR2(1));
 
CREATE OR REPLACE TRIGGER SET_TMS_UPDATE
BEFORE  INSERT OR UPDATE ON STUDENT_ITEM_SET_STATUS REFERENCING
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN

   IF :NEW.TMS_UPDATE is NULL THEN :NEW.TMS_UPDATE := 'F';
   END IF; 

   EXCEPTION
     WHEN OTHERS THEN RAISE;
END SET_TMS_UPDATE;
/