#!/bin/sh

PATH=./jre1.6.0_26/bin:$PATH
export PATH
JAVA_HOME=./jre1.6.0_26
export JAVA_HOME
JRE_HOME=./jre1.6.0_26
export JRE_HOME
java -version
java -cp ./storage/hsqldb/lib/hsqldb.jar org.hsqldb.server.Server --database.0 file:OAS --dbname.0 oas

