#!/bin/sh

PATH=./jre1.6.0_26/bin:$PATH
export PATH
JAVA_HOME=./jre1.6.0_26
export JAVA_HOME
JRE_HOME=./jre1.6.0_26
export JRE_HOME
java -version
rm ./server/apache-tomcat-6.0.29/logs/catalina.out
./server/apache-tomcat-6.0.29/bin/startup.sh

