/

CREATE TABLE LASLINK_CD_OBJECTIVE
(
  OBJECTIVE_ID        INTEGER NOT NULL,
  OBJECTIVE_NAME      VARCHAR2(200),
  TEST_LEVEL          VARCHAR2(16),
  EXT_CMS_ITEM_SET_ID VARCHAR2(32),
  SUBJECT             VARCHAR2(64)
)

/

ALTER TABLE LASLINK_CD_OBJECTIVE ADD PRIMARY KEY (OBJECTIVE_ID)


/

ALTER TABLE CUSTOMER_PRODUCT_LICENSE ADD ORDER_INDEX NUMBER
/
ALTER TABLE CUSTOMER_PRODUCT_LICENSE ADD ORDER_NUMBER VARCHAR2(9)
/
ALTER TABLE CUSTOMER_PRODUCT_LICENSE ADD PO_TEXT  VARCHAR2(30)
/
ALTER TABLE CUSTOMER_PRODUCT_LICENSE DISABLE PRIMARY KEY
/
CREATE TABLE ORGNODE_ORDER_LICENSE
(
  ORG_NODE_ID        INTEGER NOT NULL,
  ORDER_INDEX        NUMBER NOT NULL,
  AVAILABLE          	   NUMBER NOT NULL,
  LAST_LICENSE_COUNT NUMBER
)
/

CREATE TABLE FRAMEWORK_PRODUCT_PARENT
	(
  	   FRAMEWORK_PRODUCT_ID        INTEGER,
 	    FRAMEWORK_PARENT_PRODUCT_ID INTEGER
	)
/

ALTER TABLE FRAMEWORK_PRODUCT_PARENT
  	ADD CONSTRAINT FK_FRAMEWORK_PRODUCT_ID FOREIGN KEY (FRAMEWORK_PRODUCT_ID)
  	REFERENCES PRODUCT (PRODUCT_ID)
/

create sequence SEQ_LICENSE_PO_INDEX
minvalue 1
maxvalue 999999999999999999999999999
start with 100
increment by 1
cache 20

/

create or replace type NUM_ARRAY as table of number
/
CREATE OR REPLACE TYPE ROSTER AS OBJECT (roster_id NUMBER,  subtest_ids num_array)
/
CREATE OR REPLACE TYPE ROSTERARRAY AS VARRAY(1000) OF ROSTER
/
create table ITEM_RESPONSE_AUDIT
(
  ITEM_RESPONSE_ID      INTEGER not null,
  TEST_ROSTER_ID        INTEGER not null,
  ITEM_SET_ID           INTEGER not null,
  ITEM_ID               VARCHAR2(32) not null,
  RESPONSE              VARCHAR2(255),
  RESPONSE_METHOD       VARCHAR2(2) not null,
  RESPONSE_ELAPSED_TIME NUMBER(8),
  RESPONSE_SEQ_NUM      NUMBER(8) not null,
  CREATED_DATE_TIME     DATE not null,
  EXT_ANSWER_CHOICE_ID  VARCHAR2(32),
  STUDENT_MARKED        VARCHAR2(2),
  CREATED_BY            INTEGER,
  AUDIT_ID              NUMBER not null
)
/

create table ITEM_RESPONSE_POINTS_AUDIT
(
  POINTS                       INTEGER,
  ITEM_RESPONSE_POINTS_SEQ_NUM INTEGER not null,
  DATAPOINT_ID                 INTEGER not null,
  CONDITION_CODE_ID            INTEGER,
  CREATED_BY                   INTEGER not null,
  CREATED_DATE_TIME            DATE not null,
  ITEM_RESPONSE_ID             INTEGER not null,
  COMMENTS                     VARCHAR2(1000),
  AUDIT_ID                     NUMBER not null
)
/

create table ITEM_RESPONSE_CR_AUDIT
(
  TEST_ROSTER_ID       NUMBER not null,
  ITEM_SET_ID          NUMBER not null,
  ITEM_ID              VARCHAR2(32) not null,
  CONSTRUCTED_RESPONSE CLOB,
  AUDIT_ID             NUMBER not null
)
/

