package com.ctb.ejb;

import javax.ejb.MessageDrivenBean;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.ObjectMessage;

import weblogic.ejb.GenericMessageDrivenBean;
import weblogic.ejbgen.JarSettings;

import com.ctb.processor.ReportingDataProcessor;



/**
 * GenericMessageDrivenBean subclass automatically generated by Workshop.
 *
 * Please complete the onMessage method and review the MessageDriven annotation to 
 * ensure that the settings match your bean's intended use.
 */
@JarSettings(createTables = JarSettings.CreateTables.CREATE_ONLY)
@weblogic.ejbgen.MessageDriven(ejbName = "JMSRecever", 
                               destinationJndiName = "expDistributedQueue", 
                               destinationType = "javax.jms.Queue", 
                               defaultTransaction = weblogic.ejbgen.MessageDriven.DefaultTransaction.NOT_SUPPORTED, 
	maxBeansInFreePool = "10"
)
public class JMSRecever extends GenericMessageDrivenBean implements
		MessageDrivenBean, MessageListener {
	private static final long serialVersionUID = 1L;
	//private String  classExportDataVO = "ExportDataVO";
	/* (non-Javadoc)
	 * @see javax.jms.MessageListener#onMessage(javax.jms.Message)
	 */

	 
	public void onMessage(Message msg) {
		// IMPORTANT: Add your code here
		try {

			Integer object = (Integer)((ObjectMessage)msg).getObject();
			ReportingDataProcessor processor = new ReportingDataProcessor();
			processor.process(object);
			
		} catch (Exception e) {
			
			e.printStackTrace();
		}
		
	}
}







