package com.ctb.ejb;

import javax.ejb.MessageDrivenBean;
import javax.jms.Message;
import javax.jms.MessageListener;
import javax.jms.ObjectMessage;

import weblogic.ejb.GenericMessageDrivenBean;
import weblogic.ejbgen.JarSettings;

import com.ctb.processor.ReportingDataProcessor;



/**
 * GenericMessageDrivenBean subclass automatically generated by Workshop.
 *
 * Please complete the onMessage method and review the MessageDriven annotation to 
 * ensure that the settings match your bean's intended use.
 */
@JarSettings(createTables = JarSettings.CreateTables.CREATE_ONLY)
@weblogic.ejbgen.MessageDriven(ejbName = "JMSRecever", 
                               destinationJndiName = "queueoas", 
                               destinationType = "javax.jms.Queue", 
                               defaultTransaction = weblogic.ejbgen.MessageDriven.DefaultTransaction.NOT_SUPPORTED, 
	maxBeansInFreePool = "10"
)
public class JMSRecever extends GenericMessageDrivenBean implements
		MessageDrivenBean, MessageListener {
	private static final long serialVersionUID = 1L;
	//private String  classExportDataVO = "ExportDataVO";
	/* (non-Javadoc)
	 * @see javax.jms.MessageListener#onMessage(javax.jms.Message)
	 */

	 
	public void onMessage(Message msg) {
		// IMPORTANT: Add your code here
		try {
			//System.out.println("JMs hello world.............");
			/*ScheduledSessionVO scheduledSessionVO =(ScheduledSessionVO)((ObjectMessage)msg).getObject();
			Users users = scheduledSessionVO.getUsers();
			String userName = scheduledSessionVO.getUserName();
			Integer userId = users.getUserIdForName(userName);*/
			/*Object object = ((ObjectMessage)msg).getObject();
			if (object.getClass().getName().indexOf(classExportDataVO)>0){*/
			Integer object = (Integer)((ObjectMessage)msg).getObject();
			
				//System.out.println("JMS Emetric data world............."+object);
				//ExportDataVO vo = (ExportDataVO)object;
				//System.out.println("CustomerId:"+vo.getCustomerId());
				ReportingDataProcessor processor = new ReportingDataProcessor();
				processor.process(object);
			/*}*/
			
		} catch (Exception e) {
			
			e.printStackTrace();
		}
		
	}
}







