package com.ctb.lexington.data;

import java.io.Serializable;

/**
 * <p>Title: ScanUploadVO</p>
 * <p>Description: holds upload-level metadata from a scan file
 * generated by the RSU.</p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: CTB/McGraw-Hill</p>
 * @author Nate Cohen
 * @version 1.0
 */

public class ScanUploadVO implements Serializable{

    public  static final String VO_LABEL       = "com.ctb.lexington.data.ScanUploadVO";
    public  static final String VO_ARRAY_LABEL = VO_LABEL + ".array";

    // statuses
    public static final String UPLOAD_STATUS_NOT_PROCESSED = "NP";
    public static final String UPLOAD_STATUS_PENDING_VALIDATION = "PV";
    public static final String UPLOAD_STATUS_PENDING_MATCHING = "PM";
    public static final String UPLOAD_STATUS_ERROR_FILE = "EF";
    public static final String UPLOAD_STATUS_HIDDEN = "HN";
    public static final String UPLOAD_STATUS_SUCCESS = "SS";
    
    //automatch criteria 
    public static final int MATCH_STUDENTID_LASTNAME = 1000;
    public static final int MATCH_DEMO = 1001;
    
    //automatch overwrite default
    public static final String AUTOMATCH_OVERWRITE = "T";

    private Integer scanUploadId;
    private Integer userId;
    private java.util.Date uploadDate;
    private String scanUploadStatus;
	private Integer uploadedForOrgNodeId;
    private Integer automatchCriteriaId;
    private String automatchOverwrite;
	
    private String userFirstName;
    private String userLastName;
    private String uploadedFor;
    public ScanUploadVO() {
    }

    public String getUploadedFor() {
		return uploadedFor;
	}
	public void setUploadedFor(String uploadedFor) {
		this.uploadedFor = uploadedFor;
	}
   
    public String getUserLastName(){
    	return this.userLastName;
    }
    public String getUserFirstName(){
    	return this.userFirstName;
    }
    public void setUserFirstName(String userFirstName_){
    	this.userFirstName = userFirstName_;
    }
    public void setUserLastName(String userLastName_){
    	this.userLastName = userLastName_;
    }
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return userId;
    }
    public void setUploadDate(java.util.Date uploadDate) {
        this.uploadDate = uploadDate;
    }
    public java.util.Date getUploadDate() {
        return uploadDate;
    }
    public Integer getScanUploadId() {
        return scanUploadId;
    }
    public String getScanUploadStatus() {
        return scanUploadStatus;
    }
    public void setScanUploadId(Integer scanUploadId) {
        this.scanUploadId = scanUploadId;
    }
    public void setScanUploadStatus(String scanUploadStatus) {
        this.scanUploadStatus = scanUploadStatus;
    }
	public void setUploadedForOrgNodeId(Integer uploadedForOrgNodeId) {
		this.uploadedForOrgNodeId = uploadedForOrgNodeId;
	}
	public Integer getUploadedForOrgNodeId() {
		return this.uploadedForOrgNodeId;
	}
	public Integer getAutomatchCriteriaId() {
		return this.automatchCriteriaId;
	}
	public void setAutomatchCriteria(Integer automatchCriteriaId){
		this.automatchCriteriaId = automatchCriteriaId;
	}
	public String getAutomatchOverwrite() {
		return this.automatchOverwrite;
	}
	public void setAutomatchOverwrite(String automatchOverwrite) {
		this.automatchOverwrite = automatchOverwrite;
	}
	
	public boolean equals(Object object){
		boolean isEqual = false;
		try{
			ScanUploadVO su = (ScanUploadVO) object;
			if(((su.scanUploadId == null && this.scanUploadId == null) ||
				(su.scanUploadId.equals(this.scanUploadId))) &&
			   ((su.scanUploadId == null && this.scanUploadId == null) ||
				(su.scanUploadStatus.equals(scanUploadStatus))) &&
			   ((su.uploadDate == null && this.uploadDate == null) ||
				(su.uploadDate.equals(this.uploadDate))) &&
			   ((su.userId == null && this.userId == null) ||
				(su.userId.equals(this.userId)))) 
			{
				isEqual = true;
			}
		}
		catch(Exception e){
		}
		return isEqual;
	}
}