#!/bin/ksh
# FOP utility script

if [ ! $1 ] ; then
   echo "Usage: fopit xml_file_to_convert_to_pdf name_of_xsl_file"
   echo
   exit
fi

if [ ! -f $1 ]; then
  echo "File $1 does not exist!"
  exit
fi

BASEDIR=`echo $0 | sed -e "s/[1-6]//g" | sed -e "s/\/fopit//g"`
if [ ! $2 ] ; then
   XSLFILE=$BASEDIR/FOP_Interface.xsl
else
   XSLFILE=$2
fi
echo "base directory: $BASEDIR"


export LD_LIBRARY_PATH=/usr/local/lib:/usr/openwin/lib:/usr/openwin/lib/X11:/usr/dt/lib:/opt/lib:/opt/lib/X11:/oracle/product/9.0.1/lib:$LD_LIBRARY_PATH

PATH=$PATH:/opt/bin:/opt/X11/bin:/usr/bin:.:/usr/ccs/bin:/usr/ucb:/usr/openwin/bin:/oracle/product/9.0.1/bin:/export/weblogic/6.1/bin:/usr/local/bin:/usr/j2sdkee1.3.1/bin:.:/usr/ccs/bin:/usr/ucb:/usr/openwin/bin:/oracle/product/9.0.1/bin:/export/weblogic/6.1/bin:/usr/local/bin:/usr/j2sdkee1.3.1/bin:.
export PATH

CLASSPATH=/export/cim/ccs.jar
export CLASSPATH

$BASEDIR/hyphenspace.pl $1 || exit 1

TMPFILE=`echo $1.tmp | /usr/bin/sed -e 's/.xml.tmp/.temp/'`
mv $1.tmp $TMPFILE

FOFILE=`echo $TMPFILE | /usr/bin/sed -e 's/\.temp/\.fo/'`
echo "Performing XSLT of $TMPFILE with $XSLFILE to get $FOFILE"
java org.apache.xalan.xslt.Process -in $TMPFILE -xsl $XSLFILE -out $FOFILE || exit 1

PSFILE=`echo $TMPFILE | /usr/bin/sed -e 's/\.temp/\.ps/'`
PDFFILE=`echo $TMPFILE | /usr/bin/sed -e 's/\.temp/\.pdf/'`

echo
echo "Starting FOP translation for $TMPFILE to create $PSFILE"
java org.apache.fop.apps.Fop -fo $FOFILE -ps $PSFILE || exit 1

echo
echo "Transforming $PSFILE to $PDFFILE"
/usr/local/bin/ps2pdf $PSFILE $PDFFILE && echo "Created $PDFFILE Successfully!" || exit 1
echo

\rm $FOFILE $PSFILE
