#!/bin/ksh
umask g+w
if [ "$1" = "" ] ; then
   DIR="/export/cim"
else
   DIR="$1"
fi
echo GOT: $1 >> /export/cim/genSwf.log
LOGS_PATH=$DIR/logs
cd $DIR

# /usr/bin/rm $LOGS_PATH/*
/usr/bin/date >> $LOGS_PATH/printDir.txt
/usr/bin/date >> $LOGS_PATH/ibLog.txt
/usr/bin/date >> $LOGS_PATH/akLog.txt
/usr/bin/pwd >> $LOGS_PATH/printDir.txt

$DIR/uspace.pl compdisp.xml
/usr/bin/cp  compdisp.xml.usp compdisp.xml

/export/jgenerator/2.1/bin/jgenerate -log4j cab_ib.swt >> $LOGS_PATH/ibLog.txt 2>&1 || exit 1

/export/jgenerator/2.1/bin/jgenerate -log4j cab_ak.swt >> $LOGS_PATH/akLog.txt 2>&1 || exit 1





