package com.ctb.dataaccess;

public interface SiteSurveySQL {

	String GET_SITE_SURVEY_BY_ID_AND_NAME = " SELECT SITE_SURVEY_ID , SITE_ID , SITE_NAME , SITE_TYPE , SITE_PATH  FROM SITE_SURVEY WHERE SITE_ID = ? AND SITE_NAME = ? ";
	
	String GET_SITE_SURVEY_BY_ID_AND_NAME1 = " SELECT SITE_SURVEY_ID , SITE_ID , SITE_NAME , SITE_TYPE , SITE_PATH  FROM SITE_SURVEY WHERE SITE_ID = ? AND SITE_NAME = ?  AND UPPER(SITE_TYPE) = UPPER(?)";
	String GET_SITE_SURVEY_BY_ID_NAME_PATH = " SELECT SITE_SURVEY_ID , SITE_ID , SITE_NAME , SITE_TYPE , SITE_PATH  FROM SITE_SURVEY WHERE SITE_ID = ? AND SITE_NAME = ?  AND UPPER(SITE_TYPE) = UPPER(?) AND SITE_PATH = ? ";
	
	
	
	String UPDATE_SITE_SURVEY_ID_AND_NAME_PATH = "   UPDATE SITE_SURVEY SET SITE_ID = ? , SITE_NAME = ? , SITE_PATH = ? WHERE SITE_SURVEY_ID = ?";
	String UPDATE_SITE_SURVEY_SCHOOL_PATH_BELOW_THE_CORPORATION = "  UPDATE SITE_SURVEY SET SITE_PATH = REPLACE (SITE_PATH, ?, ? ) WHERE  UPPER(SITE_TYPE) = 'SCHOOL' AND SITE_PATH LIKE ?";
}
