/
create table OK_EOI_38_USER_REPLICATE
(
  OK_EOI_USER_ID     INTEGER,
  OK_EOI_ROLE_ID     INTEGER,
  OK_EOI_ORG_NODE_ID INTEGER,
  OK_38_ORG_NODE_ID  INTEGER,
  REPLICATION_STATUS VARCHAR2(10),
  CREATED_DATE_TIME  DATE,
  UPDATED_DATE_TIME  DATE
)
/

create table EOI_3TO8_USER_MAPPING
(
  USERNAME_EOI      VARCHAR2(32) not null,
  USER_ID_EOI       INTEGER not null,
  USERNAME_3TO8     VARCHAR2(32) not null,
  USER_ID_3TO8      INTEGER not null,
  ACTIVATION_STATUS VARCHAR2(2) not null,
  LAST_UPDATED      DATE not null
)
/

create table OK_EOI_38_REPLICATE_CONFIG
(
  OK_EOI_CUSTOMER_ID INTEGER,
  OK_38_CUSTOMER_ID  INTEGER,
  ACTIVATION_STATUS  VARCHAR2(2),
  CREATED_DATE_TIME  DATE
)
/