<%@ page import="java.io.*, java.util.*"%>
<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<%@ taglib uri="ctb-widgets.tld" prefix="ctb"%>

<netui-template:template templatePage="../resources/jsp/template.jsp">
    <netui-template:setAttribute name="title" value="Calendar"/>
    <netui-template:section name="bodySection">
    
    <h1>Calendar</h1>
    <p>
    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum 
    deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non 
    provident, por favor similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum 
    fuga. 
    </p>


    <netui:form action="viewCalendar">    
        <table class="transparent" >
        <tr class="transparent">
            <td class="transparent"><netui:span value="Start Date:"/></td>
            <td class="transparent">
                <netui:textBox dataSource="actionForm.startDate" tagId="startDate" maxlength="8" styleClass="textFieldDate"/>
                
                <a href="#" onclick="showCalendar(document.getElementById(getNetuiTagName('startDate'))); return false;"><img src="<%=request.getContextPath()%>/resources/images/calendar/show_calendar.gif" border="0" /></a>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr class="transparent">
            <td class="transparent"><netui:span value="Start Date2:"/></td>
            <td class="transparent">
                <netui:textBox dataSource="actionForm.startDate2" tagId="startDate2" maxlength="8" styleClass="textFieldDate"/>
                
                <a href="#" onclick="showCalendar(document.getElementById(getNetuiTagName('startDate2')), document.getElementById(getNetuiTagName('noEarlierDate'))); return false;"><img src="<%=request.getContextPath()%>/resources/images/calendar/show_calendar.gif" border="0" /></a>
            </td>
            <td>
                <netui:span value="No earlier has been specified as:" styleClass="text"/>
                <netui:textBox dataSource="actionForm.noEarlierDate" tagId="noEarlierDate" maxlength="8" styleClass="textFieldDate"/>
            </td>
        </tr>
        </table>
    </netui:form>
    
    <p>
    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum 
    deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non 
    provident, por favor similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum 
    fuga. 
    </p>
    
    </netui-template:section>
</netui-template:template>

