<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<%@ taglib uri="ctb-widgets.tld" prefix="ctb"%>

<netui-template:template templatePage="../resources/jsp/template.jsp">
    <netui-template:setAttribute name="title" value="OrderedList"/>
    <netui-template:section name="bodySection">
    
    <h1>Ordered List</h1>
    <p>
    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum 
    deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non 
    provident, por favor similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum 
    fuga. 
    </p>


<netui:form action="viewOrderedList">    


<p>      
<table class="dynamicFrame">
        
<tr class="dynamicFrame" valign="top">
    
    <!-- left table -->
    <td class="dynamicFrame" width="47%">
    <table class="dynamicFrame" height="250">
    <tr class="dynamicFrame">
        <td class="dynamicFramePane" valign="top">
    
    
        <!-- display title -->
        <table class="dynamic">
        <tr class="dynamicHeader">
            <th class="contentArea" height="25">
                <input type="hidden" id="numberOfRows" name="numberOfRows" value="3">
                Available Subtests
            </th>
        </tr>
        </table>
    
        <!-- list of rows -->
        <table class="dynamic" onselectstart="return false;">
        
        <tr id="src_row_1" class="dynamic" style="display: none" onmouseover="return hilightRow(this);" onmouseout="return unhilightRow(this);"  onmousedown="return selectRow(this);">    
            <td class="contentArea" height="25">Row 1</td>
        </tr>
        <tr id="src_row_2" class="dynamic" style="display: none" onmouseover="return hilightRow(this);" onmouseout="return unhilightRow(this);"  onmousedown="return selectRow(this);">    
            <td class="contentArea" height="25">Row 2</td>
        </tr>
        <tr id="src_row_3" class="dynamic" style="display: none" onmouseover="return hilightRow(this);" onmouseout="return unhilightRow(this);"  onmousedown="return selectRow(this);">    
            <td class="contentArea" height="25">Row 3</td>
        </tr>
         
        </table>
        
        
        </td>
    </tr>
    </table>
    </td>
    
    
    <!-- separator -->
    <td class="dynamicFrame" width="6%" align="center">
        <table class="transparent">
        <tr><td height="25">&nbsp;</td></tr>
        <tr><td><input type="button" value=">" name="addRow" id="addRow" disabled onclick="return addSelectedRow(chosenRow);" style="width:30px"/></td></tr>
        <tr><td><input type="button" value=">>" name="addAllRows" id="addAllRows" disabled onclick="return addAllSelectedRows();" style="width:30px" /></td></tr>
        <tr><td height="25">&nbsp;</td></tr>
        <tr><td><input type="button" value="<" name="removeRow" id="removeRow" disabled onclick="return removeSelectedRow(chosenRow);" style="width:30px" /></td></tr>
        <tr><td><input type="button" value="<<" name="removeAllRows" id="removeAllRows" onclick="return removeAllSelectedRows();" style="width:30px" /></td></tr>
        </table>
    </td>
    
    
    <!-- right table -->
    <td class="dynamicFrame" width="47%">
    <table class="dynamicFrame" height="250">
    <tr class="dynamicFrame"><td class="dynamicFramePane" valign="top">
    
    
        <!-- display title -->
        <table class="dynamic">
        <tr class="dynamicHeader">
            <th class="contentArea" height="25">Selected Subtests</th>
            <th class="dropDownControl" height="25">Level</th>
        </tr>
        </table>
    
        <!-- list of rows -->
        <table class="dynamic" onselectstart="return false;"> 
        
        <tr id="des_row_1" class="dynamic" style="display: inline" onmouseover="return hilightRow(this);" onmouseout="return unhilightRow(this);" onmousedown="return selectRow(this);">    
        <td class="contentArea">
            <input type="hidden" value="1" name="index_1" id="index_1" />
            Row 1
        </td>
        <td class="dropDownControl">
            <select name="level_1" size="1" style="font-family: Arial, Verdana, Sans Serif; font-size: 11px;">
                <option value="E" selected>E</option>
                <option value="M">M</option>
                <option value="H">H</option>
                <option value="A">A</option>
            </select>
        </td>            
        </tr>
 

        <tr id="des_row_2" class="dynamic" style="display: inline" onmouseover="return hilightRow(this);" onmouseout="return unhilightRow(this);" onmousedown="return selectRow(this);">    
        <td class="contentArea">
            <input type="hidden" value="2" name="index_2" id="index_2" />
            Row 2
        </td>
        <td class="dropDownControl">
            <select name="level_2" size="1" style="font-family: Arial, Verdana, Sans Serif; font-size: 11px;">
                <option value="E" selected>E</option>
                <option value="M">M</option>
                <option value="H">H</option>
                <option value="A">A</option>
            </select>
        </td>            
        </tr>


        <tr id="des_row_3" class="dynamic" style="display: inline" onmouseover="return hilightRow(this);" onmouseout="return unhilightRow(this);" onmousedown="return selectRow(this);">    
        <td class="contentArea">
            <input type="hidden" value="3" name="index_3" id="index_3" />
            Row 3
        </td>
        <td class="dropDownControl">
            <select name="level_3" size="1" style="font-family: Arial, Verdana, Sans Serif; font-size: 11px;">
                <option value="E" selected>E</option>
                <option value="M">M</option>
                <option value="H">H</option>
                <option value="A">A</option>
            </select>
        </td>            
        </tr>
        
        </table>
        
                
    </td></tr>
    </table>
    
    <!-- move up / down buttons -->                        
    <table class="transparent" align="right">
    <tr class="transparent">
        <td class="sortableControls" height="30">
            <input type="button" value="Move Up" name="moveUp" id="moveUp" disabled onclick="return moveRow( chosenRow, -1 );" />&nbsp;
            <input type="button" value="Move Down" name="moveDown" id="moveDown" disabled onclick="return moveRow( chosenRow, 1 );" />&nbsp;                  
        </td>
    </tr>
    </table>
    
    </td>
    
</tr>


</table>
</p>

 
</netui:form>
    
    <p>
    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum 
    deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non 
    provident, por favor similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum 
    fuga. 
    </p>
    
    </netui-template:section>
</netui-template:template>

