<!--Generated by WebLogic Workshop-->
<%@ page language="java" contentType="text/html;charset=UTF-8"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-databinding-1.0" prefix="netui-data"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-html-1.0" prefix="netui"%>
<%@ taglib uri="http://beehive.apache.org/netui/tags-template-1.0" prefix="netui-template"%>
<%@ taglib uri="ctb-widgets.tld" prefix="ctb"%>

<netui-template:template templatePage="../resources/jsp/template.jsp">
    <netui-template:setAttribute name="title" value="Tool Tips"/>
    <netui-template:section name="bodySection">
    
    <h1>Tool Tips</h1>
    <p>
    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum 
    deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non 
    provident, por favor similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum 
    fuga. 
    </p>
    
    <script language="javascript">
    var bigOldToolTip = ""; 
    
    bigOldToolTip += "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum";
    bigOldToolTip += "deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate.";
    </script>
    
    <h2>Heading 2</h2>
    <p>
    Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta 
    nobis est eligendi optio cumque 
    <a href="#" onclick="return false;" onmouseover="showToolTip(event, bigOldToolTip);" onmouseout="hideToolTip(event);">nihil impedit quo</a> 
    minus id quod maxime placeat facere possimus, 
    omnis voluptas assumenda est, omnis dolor repellendus. 
    </p>
    
    <h3>Heading 3</h3>
    <p>
    Temporibus autem quibusdam et aut officiis 
    debitis aut rerum necessitatibus saepe eveniet ut et 
    <a href="#" onclick="return false;" onmouseover="showToolTip(event);" onmouseout="hideToolTip(event);">voluptates repudiandae </a> 
    sint et molestiae non 
    recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus 
    maiores alias consequatur aut perferendis doloribus asperiores repellat.    
    </p>
    
    <h4>Heading 4</h4>
    <p>
    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum 
    deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non 
    provident, por favor similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum 
    fuga. 
    </p>

    <p>
    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum 
    deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non 
    provident, por favor similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum 
    fuga. 
    </p>

    <p>
    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum 
    deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non 
    provident, por favor similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum 
    fuga. 
    </p>

    <p>
    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum 
    deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non 
    provident, por favor similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum 
    fuga. 
    </p>
    
    </netui-template:section>
</netui-template:template>

